IFRCGo/go-frontend

app/assets/scripts/schemas/field-report-form.js, app/assets/scripts/utils/field-report-constants.js, app/assets/scripts/utils/network.js, app/assets/scripts/views/field-report-form.js, app/assets/styles/field-report/_form.scss, app/assets/styles/global/_page-prime-nav.scss
Includes:
- New ERU widget
- Autocomplete events
- Updated actions taken
- More field mappings
- Misc fixes
Still todo:
=> Update field report form fields

app/assets/scripts/actions/index.js, app/assets/scripts/reducers/profile.js, app/assets/scripts/views/account.js, package.json, yarn.lock
- Adds forms for controlling user subscriptions
- Creates an action to post these preferences to the API
TODO:
@danielfdsilva I'm still wrapping up work on the API side to support this, but the front-end side could be ready for a quick read if you've got a moment.
=> User notification subscriptions

app/assets/scripts/components/header.js, app/assets/styles/global/_page-prime-nav.scss, package.json, yarn.lock
I noticed that the `addeventlistener` module used in the navigation was breaking the build. It was throwing a minification error when built for production.
Ended up removing it and modifying the navigation to use the Dropdown element we already have. In the process I also corrected the html to make it more semantic.
If there was a specific need around that markup feel free to revert.
cc @derek @ascalamogna
=> Fix navigation

app/assets/scripts/components/footer.js, app/assets/styles/global/_pages.scss
=> fix navigation in footer

app/assets/scripts/actions/index.js, app/assets/scripts/reducers/index.js, app/assets/scripts/reducers/registration.js, app/assets/scripts/schemas/register.js, app/assets/scripts/utils/field-report-constants.js, app/assets/scripts/utils/format.js, app/assets/scripts/views/login.js, app/assets/scripts/views/register.js
Adds several fields to the login page to fill in data for user profiles. New views include first/last name, location, and organization.
=> Hook up login

app/assets/scripts/components/connected/alerts-table.js, app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/components/display-table.js, app/assets/scripts/utils/extendables.js, app/assets/scripts/utils/format.js, app/assets/scripts/utils/utils.js, app/assets/scripts/views/admin-area.js, app/assets/scripts/views/heops.js, app/assets/styles/global/_drops.scss
This PR adds a table comoponent which allow to easily set filters and sorts on the headers.
Check the `admin-area.js` file to see how it's implemented.
TODO on the `admin-area.js`
TODO overall;
Any question just reach out
cc @derek
=> Sort and filter

app/assets/scripts/main.js, app/assets/scripts/views/field-report.js
Redirects the user to the login page and display an alert message
=> Make deployments and heops pages private

app/assets/scripts/actions/index.js, app/assets/scripts/reducers/index.js, app/assets/scripts/reducers/situation-reports.js, app/assets/scripts/views/emergency.js, app/assets/scripts/views/home.js
@danielfdsilva this hooks up situation reports.
Right now emergencies don't really have situation reports. I added one to this emergency though:
`/emergencies/3048`
You can also add more documents to this emergency using this [the admin](https://dsgocdnapi.azureedge.net/admin/api/event/3048/change/).
Note about the admin, you can select *either* to upload a file or supply a URL. This is to support files that are already hosted elsewhere. There's no good way to enforce this in the admin, but the front-end will use the uploaded file first if there is both an uploaded file and a supplied URL.
=> Hook up situation reports

app/assets/scripts/main.js, app/assets/scripts/utils/ie.js, app/assets/styles/global/_pages.scss, gulpfile.js, package.json, yarn.lock
There are 2 major problem supporting IE11.
First one react fragments are not working (https://github.com/facebook/react/issues/11759). This was fixed and they should have a release in a week or so.
Second problem is styling. We're using flexbox for many things which is not incredibly compatible with IE11. Maybe something can be done? cc @ascalamogna 
Besides this I didn't find any other problems.
=> [WIP] IE11 support

app/assets/scripts/actions/index.js, app/assets/scripts/components/connected/presentation-dash.js, app/assets/scripts/components/homecharts.js, app/assets/scripts/reducers/overall-stats.js, app/assets/scripts/utils/format.js, app/assets/scripts/utils/fullscreen.js, app/assets/styles/global/_popovers.scss
@ascalamogna A lot more information was added to the tooltip. It may be worth to revisit the style and structure of it.
Leaving this as a WIP until you get a chance to look it over.
=> [WIP] Improve homepage charts

app/assets/scripts/actions/index.js, app/assets/scripts/components/deployments/map.js, app/assets/scripts/reducers/deployments.js, app/assets/scripts/views/deployments.js
Uses the correct acronym, which the API now uses.
=> Replace rdit with rdrt

app/assets/scripts/components/deployments/map.js, app/assets/scripts/views/deployments.js
- Adds availability and equipment units to ERU table
- Adds emergency name and link to all deployents
=> Hook up new API features to deployments page

app/assets/scripts/actions/index.js, app/assets/scripts/views/deployments.js
Also removes the available column since it's redundant.
=> Show only deployed ERUs in deployment table

app/assets/scripts/views/admin-area.js, app/assets/scripts/views/field-report-form/index.js
Fix the region page, which is throwing because of an out-of-bounds accessor.
Also change 'Event' to 'Emergency' in relevant places.
=> Fix region page, change Event to Emergency

app/assets/scripts/actions/index.js, app/assets/scripts/reducers/appeal-documents.js, app/assets/scripts/reducers/index.js, app/assets/scripts/views/emergency.js
Removes the appeals document placeholder and renders them
@danielfdsilva can you give this a look? You can check `/emergencies/6` for one that has appeal documents.
=> Hookup appeals docs

.build_scripts/az-upload.js, package.json, yarn.lock
=> Manually set mime-type on build

.circleci/config.yml, README.md, app/assets/scripts/config/production.js, app/assets/scripts/config/staging.js, package.json
FYI the `yarn build` command is now gone, it must be either `build-prod` or `build-staging`.
=> Separate config for a production deployment on master

app/assets/scripts/actions/index.js, app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/views/admin-area.js, app/assets/scripts/views/deployments.js, app/assets/scripts/views/home.js
=> Standardize and label date columns in tables

app/assets/scripts/components/emergencies/map.js, app/assets/styles/core/_tables.scss, app/assets/styles/global/_inpages.scss, app/assets/styles/home/_global.scss, app/assets/styles/home/_presenting.scss
This should fix #175 and #167. However, note i just removed all but the first three columns on the table to allow for some usability. At least this way users can navigate to emergencies and such.
=> fix mobile tables, spacing, full screens

app/assets/scripts/components/deployments/readiness.js, app/assets/scripts/components/homecharts.js, app/assets/scripts/views/deployments.js
Close #173 use country name when no national society name
=> Use country name as fallback to national society owner name

app/assets/scripts/actions/index.js, app/assets/scripts/views/deployments.js
=> Show deployed people

app/assets/scripts/components/connected/alerts-table.js
=> Add alert category to surge alerts

app/assets/scripts/components/connected/field-reports-table.js, app/assets/scripts/components/footer.js, app/assets/scripts/views/admin-area.js, app/assets/scripts/views/deployments.js, app/assets/scripts/views/home.js
=> Fix footer links

app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/components/display-table.js, app/assets/scripts/components/homemap.js, app/assets/scripts/utils/format.js, app/assets/scripts/utils/utils.js, app/assets/scripts/views/countries.js, app/assets/scripts/views/emergencies.js, app/assets/scripts/views/region.js
=> Add emergencies table to admin pages

app/assets/scripts/reducers/profile.js, app/assets/scripts/views/account.js
Re-integrate account page with new API
=> Fix account page

app/assets/scripts/components/connected/field-reports-table.js, app/assets/scripts/components/connected/user-menu.js, app/assets/scripts/reducers/fdrs.js, app/assets/scripts/views/about.js, app/assets/scripts/views/account.js, app/assets/scripts/views/countries.js, app/assets/scripts/views/deployments.js, app/assets/scripts/views/emergencies.js, app/assets/scripts/views/emergency.js, app/assets/scripts/views/field-report.js, app/assets/scripts/views/home.js, app/assets/scripts/views/login.js, app/assets/scripts/views/password-change.js, app/assets/scripts/views/recover-account.js, app/assets/scripts/views/region.js, app/assets/scripts/views/register.js, app/assets/scripts/views/uhoh.js, app/assets/styles/global/_folds.scss, app/index.html, package.json, yarn.lock
Close https://github.com/IFRCGo/go-frontend/issues/282
Close https://github.com/IFRCGo/go-frontend/issues/232
=> Fix login redirects, page titles, field report delete message

app/assets/scripts/actions/index.js, app/assets/scripts/components/connected/alerts-table.js, app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/components/connected/field-reports-table.js, app/assets/scripts/components/expandable.js, app/assets/scripts/main.js, app/assets/scripts/utils/format.js, app/assets/scripts/views/countries.js, app/assets/scripts/views/emergencies.js, app/assets/scripts/views/home.js, app/assets/scripts/views/region.js, app/assets/scripts/views/table.js, app/assets/styles/core/_tables.scss
- Standardizes the usage of table views as much as possible.
- Creates separate table views to show "all" data.
=> Include table view

app/assets/scripts/components/header.js
=> Fix elasticsearch query

app/assets/scripts/components/deployments/readiness.js, app/assets/scripts/views/deployments.js
=> Fix links, clarify table headers

app/assets/scripts/components/connected/alerts-table.js, app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/components/connected/field-reports-table.js, app/assets/scripts/components/expandable.js, app/assets/scripts/components/homemap.js, app/assets/scripts/utils/format.js, app/assets/scripts/utils/utils.js, app/assets/scripts/views/countries.js, app/assets/scripts/views/emergency.js, app/assets/scripts/views/field-report.js, app/assets/scripts/views/region.js, app/assets/scripts/views/table.js, app/assets/styles/global/_popovers.scss
Close #336 
Close #313 
Close #312 
Close #309 
Close #308 
Close #307 
Close #305
=> Fixes to appeal tables and region map updates

app/assets/scripts/actions/query-external.js, app/assets/scripts/components/connected/alerts-table.js, app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/components/connected/featured-emergencies.js, app/assets/scripts/components/connected/field-reports-table.js, app/assets/scripts/views/countries.js, app/assets/scripts/views/emergency.js, app/assets/styles/country/_global.scss
Close #323 
Close #322 
Close #265 
Close #310
=> Table filters, FDRS data properties

app/assets/scripts/actions/index.js, app/assets/scripts/reducers/countries.js, app/assets/scripts/reducers/index.js, app/assets/scripts/views/region.js, app/assets/styles/region/_global.scss
@dereklieu this adds the structure and styling for a country list on a regional page
=> add countries to region pages

app/assets/scripts/components/admin-area-elements.js, app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/views/countries.js, app/assets/scripts/views/emergency.js, app/assets/scripts/views/region.js, app/assets/styles/emergency/_global.scss
=> Hide empty boxes

app/assets/scripts/actions/index.js, app/assets/scripts/components/connected/alerts-table.js, app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/components/connected/field-reports-table.js, app/assets/scripts/reducers/csv.js, app/assets/scripts/reducers/index.js, app/assets/scripts/utils/network.js, app/assets/scripts/views/table.js
Close #325 
Data export on tables now directly initiates a CSV download of whatever data the table is showing.
=> Data export

app/assets/scripts/components/connected/alerts-table.js, app/assets/scripts/views/emergency.js
=> Emergency page alerts

app/assets/scripts/components/deployments/map.js, app/assets/scripts/components/homestats.js, app/assets/scripts/utils/format.js, app/assets/scripts/views/deployments.js, app/assets/scripts/views/field-report.js, app/assets/scripts/views/region.js
=> Text changes

app/assets/scripts/actions/index.js, app/assets/scripts/components/bullet-table.js, app/assets/scripts/components/homemap.js, app/assets/scripts/reducers/admin-area.js, app/assets/scripts/utils/utils.js, app/assets/scripts/views/countries.js, app/assets/styles/country/_global.scss
=> Filtering 3ws

app/assets/scripts/views/countries.js, app/assets/styles/country/_global.scss, package.json, yarn.lock
Close #321 
Renders country overview, key priorities, and a decimal formatted inform score, if these fields are available.
Example: http://dsgoproxyapp.azurewebsites.net/countries/14
Note that both the overview and key priorities are markdown-enabled, meaning at the very least they will properly display line breaks correctly. For more advanced users, they can even insert header and link elements.
=> Country overview 

app/assets/scripts/components/admin-area-elements.js, app/assets/scripts/components/deployments/map.js, app/assets/scripts/components/homemap.js, app/assets/scripts/views/countries.js, app/assets/styles/deployments/_global.scss
Close #225 
Legends update with data.
=> Upgrade legends

app/assets/scripts/actions/index.js, app/assets/scripts/components/connected/alerts-table.js, app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/components/connected/field-reports-table.js, app/assets/scripts/components/export-button.js, app/assets/scripts/reducers/csv.js
CSVs have no limit to the number of queried records, and now save with a filename and csv extension.
=> Improve data exports

app/assets/styles/home/_global.scss
Also fixes a mobile legend issue, partially addressing #389
=> Fix legend rendering issues

app/assets/scripts/actions/index.js, app/assets/scripts/utils/format.js
Also uses the same interval for recency (ie start of day, not end)
=> Up sitrep limit

app/assets/scripts/utils/field-report-constants.js
Hey @ElsaRaunioIFRC I noticed you pushing changes to the develop branch. Please be aware that if you push or merge anything to `develop`, it will deploy to the dev environment. As such, I'd ask that you create a separate branch from `develop` first, do your work there, then create a pull request to `develop` once you're ready. This way someone else can confirm your work before you deploy.
This adds an `\` escape character that allows you to use an apostrophe in a string.
=> Escape apostrophe

app/assets/scripts/utils/utils.js
=> Fix uniqueness function

app/assets/scripts/utils/get-new-map.js
Sets min, max zoom to 1, 6 respectively.
=> Set min, max zoom

app/assets/scripts/views/about.js
www.redcross.org/cruz-roja -> www.cruzroja.es
=> Spanish link correction in About

app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/views/countries.js
Following API #364 changes with dtype reading
=> Feature 2.1/issue 364

app/assets/scripts/components/export-button.js
Be the header more verbose and less technical hardcoded.
=> Replacements in CSV file headers

app/assets/scripts/views/emergency.js
Parallel with https://github.com/IFRCGo/go-api/pull/319
=> (Dis)allowing emergency statistics on right side

app/assets/scripts/components/connected/featured-emergencies.js
Solves https://github.com/IFRCGo/go-frontend/issues/481
=> Numeric addition in reducer

app/assets/scripts/components/homemap.js
Reverts IFRCGo/go-frontend#489
=> Revert "Errorfix/operation types"

app/assets/scripts/utils/utils.js
=> Using dtype id instead of dtype struct

app/assets/scripts/views/field-report.js
There was a list where some values were forgotten to replace.
=> Fixing displaced_affected_assisted

app/assets/scripts/reducers/emergencies.js
I had to change emergencies.js, so instead of the old const numAffected = records.reduce((acc, next) => acc + get(next, 'num_affected', 0), 0);
I had to test if there is no (non-zero) num_affected field in appeal, then get the most recent field_report belonging to it.
=> If there is no num_affected field in appeal, check the most recent field_report

app/assets/scripts/components/export-button.js
Solves https://github.com/IFRCGo/go-frontend/issues/364
country society_name > national_society_name
code > appeal_code
=> Issue 364: Some more replacement rules

app/assets/scripts/components/export-button.js
=> Issue 364: Use only dashes in CSV header

app/assets/scripts/components/connected/field-reports-table.js
=> More links for regions

app/assets/scripts/actions/index.js, app/assets/scripts/components/connected/emergencies-dash.js, app/assets/scripts/views/emergencies.js
To widen map interval from 30 to 90 days
=> getLastMonthsEmergencies to getLast3MonthsEmergencies

app/assets/scripts/views/emergency.js, app/assets/styles/emergency/_global.scss, app/assets/styles/global/_inpages.scss, app/assets/styles/settings/_variables.scss
To address https://github.com/IFRCGo/go-frontend/issues/424
=> Format and style emergency sources

app/assets/scripts/components/form-elements/input.js, app/assets/scripts/views/field-report-form/index.js
Summary limitation to 100 characters
=> Summary limitation to 100 characters

app/assets/scripts/components/connected/emergencies-table.js, app/assets/scripts/components/footer.js, app/assets/scripts/views/home.js
And fixing 2 typos (2018->2019, Go->GO)
=> Splitting emergencies according to regions

app/assets/scripts/components/header-region-button.js, app/assets/scripts/utils/region-constants.js, app/assets/scripts/views/countries.js, app/assets/scripts/views/region.js, package.json, yarn.lock
- country and region
- Added [memoize](https://github.com/alexreardon/memoize-one)
=> Add support for id and name in

app/assets/scripts/views/account.js
Subscription possibilities, following the wireframe plan.
=> PER Due Dates and 3 surge types on account page

app/assets/styles/global/_inpages.scss, app/assets/styles/home/_global.scss
fixes weird alignment of figures on region pages
=> fix page intro global styles, make them local

app/assets/styles/emergency/_global.scss, app/assets/styles/global/_inpages.scss
- Fix alignment of "All Appeals" on Emergency page
- Make tab buttons bolder
=> Minor alignment issues / bolden tabs

.eslintrc, yarn.lock
Eliminating some historical module versions.
=> Rerun yarn install with empty yarn lock file

app/assets/scripts/schemas/field-report-form.js, app/assets/scripts/views/field-report-form/cmp-source-estimation.js, app/assets/scripts/views/field-report-form/data-utils.js, app/assets/scripts/views/field-report-form/index.js, app/assets/styles/field-report/_form.scss
Adds start_date and "Other" source.
It would be nice to give this a bit of a thorough test before merging. @szabozoltan69 if you are able to test this and it works, please feel free to merge, otherwise I will give it a look again in the morning.
=> Field report fields: add Other source and start_date

app/assets/scripts/views/field-report-form/cmp-contact-row.js, app/assets/scripts/views/field-report-form/data-utils.js, app/assets/styles/field-report/_form.scss
cc @szabozoltan69 
If you are able to do a quick check and merge, hopefully @mmusori can test further -- this adds the "Phone Number" field to the Contact info on the Field Report.
I will make the other changes mentioned in the document now / bringing text in line with Invision, etc.
=> Adds field for Contact - Phone to Field Report

app/assets/scripts/views/field-report-form/cmp-contact-row.js
@szabozoltan69 this should fix the errors with the new phone field, thank you for the catch!
=> oops, forgot to set values of email / phone fields correctly

app/assets/scripts/components/form-elements/checkable.js, app/assets/scripts/components/form-elements/radio-group.js, app/assets/scripts/views/field-report-form/cmp-planned-response-row.js, app/assets/scripts/views/field-report-form/index.js
@szabozoltan69 this should achieve allowing the user to unselect radios in the Planned Response section of the Field Report.
Let's wait maybe 15-20 minutes before merging because I need to think about what I did here for a little bit, and just try to think if it will cause any problems.
=> ugly hack to let user unselect a radio button under Planned Response

app/assets/scripts/components/connected/alerts-table.js, app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/components/country/preparedness-overview.js, app/assets/scripts/components/header.js, app/assets/scripts/components/homecharts.js, app/assets/scripts/components/preparedness/global-preparedness-highlights.js, app/assets/scripts/components/preparedness/national-societies-engaged-per.js, app/assets/scripts/components/preparedness/preparedness-header.js, app/assets/scripts/views/preparedness.js, app/assets/styles/core/_tables.scss, app/assets/styles/global/_charts.scss, app/assets/styles/global/_forms.scss, app/assets/styles/global/_page-prime-nav.scss, app/assets/styles/home/_global.scss, app/assets/styles/preparedness/_global.scss, app/assets/styles/settings/_variables.scss
=> Miscellaneous UI fixes

app/assets/scripts/components/per-forms/per-form-component.js, app/assets/scripts/components/preparedness/global-preparedness-highlights.js, app/assets/scripts/views/field-report-form/index.js, app/assets/styles/core/_base.scss, app/assets/styles/core/_tables.scss, app/assets/styles/emergencies/_global.scss, app/assets/styles/field-report/_form.scss, app/assets/styles/field-report/_global.scss, app/assets/styles/global/_page-prime-nav.scss, app/assets/styles/home/_global.scss, app/assets/styles/settings/_mixins.scss
- Updates to PER form styling to make more consistent with Field Report forms
- Fix "Submit" button text on last Step of Field Report submission
- Make Select dropdowns on Field Report consistent
- Improve styling of search box
- Add some styling for Global Preparedness Highlights table
cc @szabozoltan69
=> PER Form Updates and misc design changes

app/assets/scripts/components/per-forms/overview-form.js
=> Reset button to Overview form

app/assets/scripts/utils/get-new-map.js, app/assets/styles/global/_inpages.scss, app/assets/styles/home/_global.scss
=> change basemap style

app/assets/styles/core/_tabs.scss
- remove bottom border of selected tab
- highlight colour of selected tab
- text transform and letter spacing
cc @szabozoltan69
=> improve styling of tabs

app/assets/scripts/views/account.js
=> add help texts to notification check-boxes

app/assets/scripts/components/map/home-map.js, app/assets/scripts/components/map/home-map/appeal-types-dropdown.js, app/assets/scripts/components/map/home-map/emergency-types-dropdown.js, app/assets/styles/global/_forms.scss, app/assets/styles/home/_global.scss, app/assets/styles/settings/_variables.scss
=> move filter dropdowns on home map, styling to match designs

app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/components/connected/presentation-dash.js, app/assets/scripts/views/home.js
=> reorder elements on homepage as per design

app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/components/connected/presentation-dash.js, app/assets/scripts/components/homestats-component.js, app/assets/styles/home/_presenting.scss
Hide elements on fullscreen view, improve styling.
Towards #765
=> fullscreen styling, hide elements

app/assets/scripts/components/connected/appeals-table.js, app/assets/scripts/components/display-table.js
Make date filter a date range filter. Pending styling.
=> allow date range filter in operations filters

app/assets/scripts/components/display-table.js, app/assets/styles/core/_typography.scss, app/assets/styles/global/_forms.scss, app/assets/styles/home/_global.scss
Basic styling for date range filter, fixes #764
=> Date range styling

app/assets/scripts/utils/utils.js, app/assets/scripts/views/emergency.js, app/assets/styles/emergency/_global.scss, app/assets/styles/global/_folds.scss, app/assets/styles/global/_scrollbar-custom.scss, app/assets/styles/main.scss
Organize the Response Documents on the Emergency Page with a card layout, toward #773 .
=> Response doc cards #773

app/assets/scripts/views/countries.js
=> adds RC before homepage on country link, fixes #795

app/assets/scripts/components/tab-content.js, app/assets/scripts/views/countries.js, app/assets/scripts/views/emergency.js, app/assets/scripts/views/region.js, app/assets/styles/core/_utilities.scss, app/assets/styles/emergency/_global.scss, app/assets/styles/global/_buttons.scss
=> [wip] Emergency page redesign

app/assets/scripts/views/region.js
=> move map and operations table above country list, fixes #809

app/assets/scripts/views/emergency.js
Hide source for situational overview on Emergency Page, as per discussion
=> hide source for situational overview

app/assets/scripts/components/connected/user-menu.js
=> ensure handleWindowSizeChange has the correct scope of this

app/assets/scripts/components/per-forms/form-data/a3-2/english-data.js, app/assets/scripts/components/per-forms/per-form.js
FIxing 14A unnecessary benchmark.
Fixing mandatory fields requirement when draft saving.
=> Fix PER bugs v1

app/assets/scripts/actions/index.js, app/assets/scripts/reducers/per-form.js, app/assets/scripts/views/account.js, app/assets/styles/forms/per-form.scss
Making this a Pull Request so it is easier to organize comments @GregoryHorvath 
WARNING: This PR should not be merged until the backend branch to implement deletion is merged and deployed: https://github.com/IFRCGo/go-api/pull/534
@GregoryHorvath I pushed a fix for the issue of the page not refreshing the draft list after you delete.
All this PER code could probably be structured better and this is not ideally how I'd do it, but this works - let me know if you want to talk a bit about that code and I can explain exactly what it is doing.
=> [WIP] Delete PER draft

gulpfile.js, package.json, yarn.lock
Remove dependency on forked react.
Should fix weird errors on staging.
cc @frozenhelium
=> Fix conflicting React versions

app/assets/scripts/views/emergency.js
Concerns to https://github.com/IFRCGo/go-api/issues/535
=> Fixed Emergency Document URL

app/assets/scripts/views/region.js
Moves graph to be below map/chart on region page as requested in #864
=> moves graph on region

app/assets/scripts/actions/index.js, app/assets/scripts/views/ThreeW/index.js, app/assets/scripts/views/ThreeW/project-form.js, app/assets/scripts/views/ThreeW/table.js, app/assets/scripts/views/countries.js
* Add `Actions` column to project table
* Add `Edit` button to edit project in the actions column
* Hid `Add` button in 3W page if user is not logged in
=> Make projects editable for logged in users

app/assets/scripts/components/common/key-figures-header.js, app/assets/scripts/views/countries.js
=> Fix type error in country page and key-figures-header

app/assets/scripts/utils/field-report-constants.js, app/assets/scripts/views/field-report-form/cmp-source-estimation.js, app/assets/scripts/views/field-report-form/index.js
As per https://github.com/IFRCGo/go-frontend/issues/833#issuecomment-562146655
=> Minor changes to field report labels, texts

app/assets/scripts/views/countries.js
This reverts commit 8b1f3e05dd20b0433a0b779826e4de93cc57a536.
cc @frozenhelium
=> Revert "Hide 3w tab in countries page"

app/assets/scripts/views/field-report.js
=> Added summary of Actions Taken for Field Reports

app/assets/scripts/components/per-forms/per-account-tab.js
#918 
Adds a filter to only display countries with a `Result Type` of `Country`
=> PER country list filter

app/assets/scripts/components/per-forms/form-data/a2/english-data.js, app/assets/scripts/components/per-forms/form-data/a3-2/english-data.js, app/assets/scripts/components/per-forms/form-data/a5/english-data.js
Makes the 3 fixes to PER question texts, as per #947 
@necoline would be great if you could review / merge. Thanks!
=> text fixes to PER forms, as per #947

app/assets/scripts/components/country/preparedness-column-graph.js, app/assets/scripts/components/country/preparedness-summary.js, app/assets/scripts/utils/get-per-components.js
#950  
- Makes call to retrieve PER Component values hopefully a bit easier to read
- Adds a fallback in the case that the result of the `getPerComponent` is `undefined`
- Adds an error message to highlight the missing values
- Adds a default value to list os possible hardcoded values
=> adds fallback

.github/ISSUE_TEMPLATE/bug-report---staging.md
Merge changes from master to deal with build process updates back into develop to prepare for new release.
=> Merge master

app/assets/scripts/components/per-forms/per-account-tab.js, app/assets/scripts/components/per-forms/per-form.js
Fixes PER form to get country id correctly.
=> ref #973 - fixes cases where country id would be null on per form submission

app/assets/scripts/views/field-report-form/data-utils.js, app/assets/scripts/views/field-report-form/index.js
Populate action checkboxes correctly when Editing a Field Report.
=> fix correctly loading actions in field report edit, ref #984

app/assets/scripts/utils/format.js, app/assets/scripts/views/field-report-form/data-utils.js, app/assets/scripts/views/field-report.js
Refs #985.
This PR fixes:
- Add Start Date to Field Report display (with different title based on EW / Event)
- Add Information Bulletin info to Field Report display
- Show `Description` label as `Risk Analysis` for EW field reports
- Fix display of Contact Title while editing Field Report form.
A separate fix to fix display of Phone number in Field Report form is addressed in https://github.com/IFRCGo/go-api/pull/627
cc @nanometrenat
=> Fix Field Report fields on frontend

app/assets/scripts/components/connected/alerts-table.js
Fix for @teklal's comment on #965.
Also could be interesting for #940.
=> Added Rapid Response to Surge Notif. types

README.md, package.json, yarn.lock
Introduces yarn commands to deploy a branch to surge.sh and teardown once testing is complete. 
cc @batpad
=> Deploy to Surge.sh

app/assets/scripts/components/connected/personnel-table.js
Ref: https://github.com/IFRCGo/go-frontend/issues/965#issuecomment-600523650
=> Added RR to Types filter for deployed personnel

app/assets/scripts/views/deployments.js
Ref: https://github.com/IFRCGo/go-frontend/issues/965#issuecomment-601071308
=> [PROD] Handled if any of the Deployments RRs are undef.

app/assets/scripts/components/emergencies/snippets.js, app/assets/scripts/components/footer.js, app/assets/scripts/main.js, app/assets/styles/global/_pages.scss
Ref.: https://github.com/IFRCGo/go-frontend/issues/888
=> Removed current CSS, added banner for staging

app/assets/scripts/utils/utils.js
Address https://github.com/IFRCGo/go-frontend/issues/1008#issuecomment-608344198
=> sort pinned items in descending order

app/assets/scripts/views/emergency.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1010#issuecomment-607476830
=> Redirect merged Emergencies' links to parents

package.json
=> fix surge routing by using a 200.html

app/assets/scripts/components/emergencies/snippets.js
addresses https://github.com/IFRCGo/go-frontend/issues/1086
cc @batpad @necoline
=> for events with no snippets show a message instead of returning

app/assets/scripts/views/emergency.js
Should go along with https://github.com/IFRCGo/go-api/pull/661
cc @GregoryHorvath @batpad @necoline
=> if event or profile is 404, check that before trying to render

app/assets/scripts/views/field-report-form/cmp-action-checkboxes.js, app/assets/scripts/views/field-report.js
#1096 
https://ifrc-go-fix-1096-report-summary.surge.sh/
=> reorganizes summary

app/assets/scripts/actions/index.js
Raises action limit to 500
#1098
=> Raises action limit

app/assets/scripts/utils/utils.js, app/assets/scripts/views/emergency.js, package.json, yarn.lock
Add the response docs bits because they got dropped in a merge.
=> bring response docs back

app/assets/scripts/views/field-report-form/index.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1077
=> Create Field Report error message

CHANGELOG.md
@geohacker can I ask for a quick approve on this? Have added release notes for previous two releases and setup a CHANGELOG.md file to use for release notes for future releases.
=> adds CHANGELOG with details of previous two releases

app/assets/scripts/components/emergencies/snippets.js
This addresses https://github.com/IFRCGo/go-frontend/issues/1009#issuecomment-613909224
cc @batpad
=> if there are no snippets for a tab, don't break

app/assets/scripts/components/footer.js, app/assets/scripts/views/about.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1069
=> Fix API link in footer and About PDF links

app/assets/scripts/views/field-report.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1096#issuecomment-615884458
=> Reorder Planned data on Field Report page

app/assets/scripts/views/emergency.js, app/assets/styles/country/_global.scss, app/assets/styles/emergency/_global.scss
Ref.: https://github.com/IFRCGo/go-frontend/issues/1097
Requires: https://github.com/IFRCGo/go-api/pull/680
=> Added EPI figures to Emergency page

app/assets/scripts/utils/get-per-components.js
cc @GregoryHorvath would be great to merge this so we can test if this fully fixes this issue, frontend and backend.
=> switch component mappings for 3 and 3.2, refs #1137

app/assets/scripts/views/emergency.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1097#issuecomment-620040522
=> Hide EPI data from Emergency page

app/assets/scripts/components/global-header-banner.js
Refs https://github.com/IFRCGo/go-frontend/issues/1007#issuecomment-619991134
=> fix text on covid-19 banner

app/assets/scripts/schemas/field-report-form.js, app/assets/scripts/views/field-report-form/data-utils.js, app/assets/scripts/views/field-report-form/index.js, app/assets/scripts/views/field-report.js
#1160 
Current status of PR: https://github.com/IFRCGo/go-frontend/issues/1160#issuecomment-622404825
Surge URL: https://ifrc-go-feature-1160-covid-fr.surge.sh/reports/new
=> COVID-19 field report

app/assets/scripts/schemas/register.js
Ref.: https://github.com/IFRCGo/go-api/pull/704
**Change of plans: good enough to include this with the next official deployment.**
~~- [ ] Merge `master` into `develop`~~
=> Added redcrossnigeria.org to domain whitelist

CHANGELOG.md, app/assets/scripts/components/about/video-carousel.js, app/assets/scripts/schemas/register.js, app/assets/styles/about/_global.scss, package.json
Minor hotfix release:
- Adds additional video as per https://github.com/IFRCGo/go-frontend/issues/1216
- Add to whitelist domains
=> Hotfix Release 4.3.2

app/assets/scripts/reducers/domain-whitelist.js, src/root/actions/index.js, src/root/reducers/domain-whitelist.js, src/root/reducers/index.js, src/root/reducers/registration.js, src/root/reducers/subscriptions.js, src/root/schemas/register.js, src/root/utils/utils.js, src/root/views/register.js
Requires: https://github.com/IFRCGo/go-api/pull/709
=> Domain whitelist using the API instead of a static list

src/root/components/per-forms/overview-form.js
Allow years from 2010 - 2023 in PER overview form year dropdowns
Refs #1230
=> refs #1230 - add years from 2010 - 2023 in PER overview form years

src/root/views/emergency.js, src/root/views/field-report.js
=> Hide 'Delegates' from COVID FRs

src/root/views/register.js
Changed wording of account from "existing" to "active"
=> Changed wording

src/root/components/connected/emergencies-table.js
Surge: https://ifrc-go-fix-1132-recent-emergencies.surge.sh
Reverts the previous PR and makes the recency interval different on country pages.
=> Make condition for showRecent more specific to country pages

src/root/components/error-panel.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1232
=> Hide header if there is no data

src/root/actions/index.js, src/root/components/ThreeWSankey/index.js, src/root/components/ThreeWSankey/styles.module.scss, src/root/index.js, src/root/views/Covid19ThreeWSankey/Filters.js, src/root/views/Covid19ThreeWSankey/index.js, src/root/views/Covid19ThreeWSankey/styles.module.scss
Depends on: https://github.com/IFRCGo/go-api/pull/745
Related to: https://github.com/IFRCGo/go-frontend/issues/1284
Test link: https://ifrc-go-feature-global-3w-sankey.surge.sh/covid19-3w-sankey
=> Add covid19 3W sankey page

src/root/components/ThreeWSankey/index.js, src/root/components/ThreeWSankey/styles.module.scss, src/root/hooks/index.js, src/root/views/Covid19ThreeWSankey/index.js, src/root/views/Covid19ThreeWSankey/styles.module.scss
Depends on: https://github.com/IFRCGo/go-api/pull/747
=> Exclude domestic projects for 3W covid19 sankey

src/root/views/account.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1212
=> Fix duplicated countries after subscr. saving

src/root/views/field-report-form/index.js, src/root/views/per-forms.js, src/root/views/preparedness.js
Fix page titles as per #1125 and #997
=> Fix page titles

.babelrc.js, package.json, yarn.lock
Related to: https://github.com/IFRCGo/go-frontend/issues/1314
=> Use preset-env to support old browsers

src/root/components/expandable.js
Ref.: https://github.com/IFRCGo/go-api/pull/773
=> Add <p> around Expendable text for RTE

src/root/schemas/field-report-form.js
Refs #1141 - makes the title field on the field report mandatory.
=> make title a required field on field reports

src/root/components/expandable.js
Ref.: https://github.com/IFRCGo/go-api/issues/670
=> Rolled back <p> for RTE

src/root/views/view-per-forms.js
=> fix breadcrumbs in view PER form pages

src/root/components/expandable.js
Ref.: https://github.com/IFRCGo/go-api/issues/670
=> Added <p> tag back for RTE backend changes

src/root/views/ThreeW/project-form.js
Depends on:
* https://github.com/IFRCGo/go-api/pull/787
Related to:
* https://github.com/IFRCGo/go-frontend/issues/1319
* https://github.com/IFRCGo/go-frontend/issues/1334
=> Update country project form schema according to ICRC requirements

README.md
Minor README fix
cc @GregoryHorvath @frozenhelium
=> fix build instructions for surge deploy to build-staging

src/root/views/emergency.js
Depends on this backend PR: https://github.com/IFRCGo/go-api/pull/789
Refs #1122
=> display country and region on field reports on emergency page

src/root/views/emergency.js
=> fix Add Report link on emergency page to go to correct page on admin

src/root/components/per-forms/overview-form.js
Oops, had forgotten to PR / merge this :facepalm:
Ref #1230
=> extend date range on per overview form to 2030, refs #1230

src/root/views/view-per-forms.js
=> Fix page title on View PER Form pages

src/root/views/ThreeW/project-form.js
Related to: https://github.com/IFRCGo/go-frontend/issues/1378
=> Fix project form context type typo

src/root/actions/index.js, src/root/lang.js, src/root/views/register.js, src/styles/core/_typography.scss
Ref.: https://github.com/IFRCGo/go-frontend/issues/1233
Covers all 4 check-points.
Backend requirement: https://github.com/IFRCGo/go-api/pull/816
=> Registration page improvements

CHANGELOG.md, package.json, src/root/components/header.js, src/styles/global/_page-prime-nav.scss, src/styles/global/_pages.scss
As per #1363 - add links to KoBo forms on GO.
TODO before we can merge:
After merging:
=> Hotfix: Add dropdown for field reports

src/root/views/countries.js, src/root/views/emergency.js, src/styles/core/_base.scss, src/styles/core/_tabs.scss, src/styles/emergency/_global.scss, src/styles/global/_folds.scss, src/styles/home/_global.scss
Add new grid and consistent styling for Key numbers, Emergency overview, Tabs, Folds and responsive styling for page.
Note: Actual issue is #1408  so name of branch is kind of incorrect :p apologies.
=> #1408: Add styling for emergency detail page

src/root/components/highlighted-operations/operation-card.js, src/styles/home/_global.scss, src/styles/home/_highlighted-emergencies.scss, src/styles/settings/_variables.scss
Increase font size in highlighted ops card
Revery key numbers to previous width and margin
=> Increase font size for highlighted ops

src/root/views/register.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1233#issuecomment-660989167
=> Exclude 'ICRC' from the NS list

src/root/lang.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1370
Wanted to adjust the related variable names as well, but after checking, even the API calls it "subscribe" so in the end I only changed the text here.
=> Change (Un)subscribe to (Un)follow

src/root/views/ThreeW/table.js, src/styles/country/_global.scss
Addiing @lauripynnonen here for the visibility, I've removed the *Last Updated* column.
=> Fix country 3W overflow, remove last updated column

src/root/components/header.js
* Fix the behaviour where search was not debouncing and sending request for each character typed
* Fix the state when it showed loading even on empty string
@GregoryHorvath can you verify that this fix reflects the behaviour that is consistent with the current production environment?
CC: @batpad for visibility
=> Fix search behaviour

src/root/components/map/emergency-map.js, src/root/views/countries.js, src/root/views/emergency.js, src/styles/core/_typography.scss, src/styles/country/_global.scss, src/styles/emergency/_global.scss, src/styles/global/_inpages.scss, src/styles/home/_global.scss
Match spacing to Zeplin for Emergency and Country page h1 heading 
Improve styling for key numbers on this URL: emergencies/3789#details
=> #1448: Fix spacing issues for Emergency and Country page

src/root/components/connected/alerts-table.js
@imohkay not sure why those TRs were being added exactly. Removed in this PR, if it looks good, please merge.
Ref #1461
=> remove extra presentations trs from alerts table, ref #1461

src/root/views/account.js, src/styles/global/_buttons.scss
=> #1471: Unfollow button child span now accepts click

package.json
Thanks @frozenhelium @geohacker !
Could one of you please review / approve? I have tested deploy and teardown both using this branch name (`fix/surge.deploy`) and it seems to work fine. Would like to merge this to develop soon and get this commit into the release branch. Thanks!
=> fix surge deploy scripts to also replace dots with dashes

src/root/Multiplexer/index.js, src/root/Multiplexer/styles.module.scss, src/root/components/AnonymousRoute.js, src/root/components/PrivateRoute.js, src/root/components/block-loading.js, src/root/components/spinner.js, src/root/index.js, src/root/selectors/index.js, src/root/views/login.js
Related to: https://github.com/IFRCGo/go-frontend/issues/1386
=> Create a framework to load initial data for app

src/root/views/emergency.js
=> fix grey screen on emergency pages not associated with a country

src/root/views/emergency.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1501
Backend PR: https://github.com/IFRCGo/go-api/pull/846
Same PR but towards `master`: https://github.com/IFRCGo/go-frontend/pull/1502
=> IFRC Admins now see IFRC Field Reports too

src/root/components/map/emergencies-map.js
Hotfix for broken map on emergency page.
cc @GregoryHorvath @geohacker
=> fix points on emergencies page map not showing up

src/styles/settings/_variables.scss
@frozenhelium  Hey I just added the font sizes in comments in the variables files. Hopefully, this should be of help to you.
=> #1321: update font sizes in pixels in commments in variables

src/root/components/common/filters/date-filter-header.js, src/root/components/connected/user-menu.js, src/root/components/display-table.js, src/root/components/dropdown-menu.js, src/root/components/header-region-button.js, src/root/components/header.js, src/root/components/mobile-header.js, src/styles/components/_dropdown-menu.scss, src/styles/global/_page-prime-nav.scss, src/styles/home/_global.scss
TODO: fix styling in following components
* `components/mobile-header.js`
* `components/common/filters/date-filter-header.js`
* `components/header.js`
* `components/display-table.js`
* `components/header-region-button.js`
* `components/connected/user-menu.js`
will resolve: https://github.com/IFRCGo/go-frontend/issues/1560
=> Replace old dropdown with new dropdown menu

src/root/components/connected/user-menu.js, src/styles/components/_dropdown-menu.scss, src/styles/global/_drops.scss, src/styles/global/_page-prime-nav.scss
Small PR to make the styling on user dropdown closer to original. Also removed the black outline on focus on the dropdown for Regions in the menu.
=> #1560: Fix styling issues with dropdowns on navigation

src/root/components/highlighted-operations/operation-card.js
@batpad for some reason there was an emergency with no title, that's what was causing the issue for Daniel
Related to: https://github.com/IFRCGo/go-frontend/issues/1577
=> Add check for empty operation name in operation-card

src/root/views/register.js
Fix showing country dropdown and organization dropdown on the register page.
Refs #1541
=> fix countries appearing on register page

src/root/Multiplexer/index.js
=> fix lint, remove unused var

src/root/Multiplexer/index.js, src/root/utils/request.js, src/root/views/ThreeW/project-form.js, src/root/views/register.js
Related to: https://github.com/IFRCGo/go-frontend/issues/1589
=> Use country selector instead of using it directly from the state

src/root/views/account.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1604
Countries labels fix
=> Fix Notifications countries labels

src/root/views/ThreeW/project-form.js
Addresses https://github.com/IFRCGo/go-frontend/issues/1534#issuecomment-694915830
cc @jhenshall @batpad @GregoryHorvath
=> show only independent countries in the 3w form

src/root/reducers/emergencies.js
Thanks for catching @frozenhelium
=> make sure centroid prop exists

src/root/utils/field-report-constants.js, src/root/views/register.js
fix registration page country dropdown to use the countries from state and dropdown util. ensure clusters are not listed on the field report form dropdown
=> Fix Country dropdowns, yet again

src/root/views/register.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1627
- Fixes National Societies' dropdown on the Register page
=> Fix NS dropdown on Register page

src/root/actions/index.js, src/root/utils/network.js, src/root/views/field-report-form/index.js
Make it so that the field report form when editable always shows english strings. Refs #1625
=> when editing a field report, always fetch english strings, refs #1625

src/root/utils/get-new-map.js
Fixes https://github.com/IFRCGo/go-frontend/issues/1629
cc @batpad  @jhenshall
=> Don't cut the map at 180

src/root/components/global-header-banner.js, src/root/lang.js
Show a survey link instead of COVID banner.
=> Survey instead of COVID header

src/root/components/global-header-banner.js
Make the Survey open in a new tab.
=> Open banner link in new tab

src/root/components/map/emergency-map.js, src/root/selectors/index.js, src/root/views/emergency.js
=> Multilingual country label fixes

src/root/utils/field-report-constants.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1654
cc @batpad
=> Fix Early Action step3 RCRC label

CHANGELOG.md, package.json, src/root/views/app.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1675
@batpad this was branched from and points to `master`, not sure how urgent it is to merge, just wanted to make sure we can if we need to
- Removes the Global banner at the top of the page
=> Comment out Global banner

package.json, src/root/components/form-elements/input.js, src/root/components/per-forms/per-form.js, src/root/views/per-assessment.js, src/wdyr.js, yarn.lock
- Changes `useState` to `useReducer` for complex nested state
- Makes the text input form a pure component using `React.memo`
- Memoizes the `handleChange` callbacks using `useCallback`
=> Add reducers and memos

src/root/components/admin-area-elements.js, src/root/views/countries.js, src/root/views/region.js
Refs #1621 - remove the Additional Graphics header on the country page.
=> remove header in country additional tab, fix title in regional tab

src/root/views/countries.js
=> remove inform score from countries

src/root/components/header.js, src/root/lang.js, src/root/views/preparedness.js
- Updated dashboard links and namings, coming from Shirin
=> Update dashboard urls, title, summary

src/root/components/map/deployments-map.js
=> Fix deployments map

src/root/components/admin-area-elements.js, src/root/components/connected/presentation-dash.js, src/root/components/map/home-map/explanation-bubble.js, src/root/components/map/home-map/factory/marker-layer-stylesheet-factory.js, src/root/components/map/home-map/operations-popover.js, src/root/components/map/main-map.js, src/root/utils/get-new-map.js, src/root/views/region.js, src/styles/components/_common.scss, src/styles/global/_folds.scss, src/styles/region/_global.scss
Fixes https://github.com/IFRCGo/go-frontend/issues/1202
=> Map style updates

src/root/views/per-assessment.js, yarn.lock
Ref.: https://github.com/IFRCGo/go-frontend/issues/1667
Probably fix for data-incosistency issue after the redirect when creating a new Assessment.
=> Fix state for create Assessment

src/root/views/per-assessment.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1667
Hopefully fixes that opening any Overview sometimes showed one specific Overview's data.
cc @batpad
=> Fix PER Overview data inconsistency

src/root/components/per-forms/per-account.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1667
- Fixes the Included Forms fields' data in the PER list
=> Add included_forms data to the PER list

src/root/views/preparedness.js
Ref.: #1669 
Hardcoded the heights of `<iframe>`s so the inside scrollbar disappears.
=> Hardcode iframe heights

src/root/views/emergency.js
Fixes Emergency page grey-screen for non-logged in users.
Refs #1243
=> handle case of response being an error, dont fail page

src/root/components/timeline-charts.js
=> Fix missing months in chart

src/root/components/preparedness/preparedness-header.js, src/root/views/preparedness.js
=> Made the Preparedness logo bigger, fix iframe heights

src/root/components/preparedness/preparedness-header.js
=> Make Preparedness logo and text col-6

src/root/components/per-forms/per-form.js, src/root/views/per-assessment.js, src/styles/forms/per-form.scss
Ref.: #1667 
- Add uncheck radio button to each question
=> Uncheck radio button

src/root/views/per-assessment.js
Ref.: #1667 
- Fix messages and hide loading if a bad request response comes back from the API
=> Fix error messages for create/update/delete

src/root/components/per-forms/per-form.js
Ref.: #1667 
- Fix for the radio uncheck button also showed up in View mode
=> Remove uncheck button from View mode

src/root/components/map/emergencies-map.js, src/root/components/map/emergency-map.js, src/root/components/map/home-map/operations-popover.js, src/root/views/emergency.js, src/styles/core/_base.scss, src/styles/field-report/_form.scss, src/styles/forms/per-form.scss, src/styles/global/_forms.scss, src/styles/global/_popovers.scss, src/styles/settings/_mixins.scss
#1740: Map Popovers: Improve map close icon on hover, correct font weights and hover for titles, line separators
#1740: Center emergency map when solo
#1740: Style checkbox with trash icon for field report and PER forms
=> Feature/1740 UI fixes deploy

src/root/selectors/index.js
=> Remove accidental import

src/root/components/connected/all-personnel-table.js, src/root/views/table.js
=> add separate component to display all personnel deployments table

src/root/components/map/main-map.js
cc @geohacker - I just commented out the map hover bits, could you review?
=> remove country on hover highlight on map, refs #1740

src/root/components/map/emergencies-map.js, src/root/components/map/home-map/explanation-bubble.js, src/root/components/map/home-map/factory/marker-layer-stylesheet-factory.js, src/root/views/region.js, src/styles/home/_global.scss
=> More map updates

src/root/components/map/deployments-map.js, src/root/utils/country-labels.js
=> make the labels black. make sure deployments map follow map style guide

src/root/lang.js, src/root/views/emergency.js
=> enable frontend search for response documents

src/root/utils/get-new-map.js
=> Adds RTL plugin for mapbox maps

src/root/views/preparedness.js
=> Adjust Performance tab height

src/root/components/form-elements/error.js, src/root/views/per-assessment.js, src/styles/forms/per-form.scss
Validation error messages were showing up as 'undefined'.
cc @batpad
=> Fix error messages were 'undefined'

src/root/utils/country-labels.js
=> poppins isn't rendering rtl well, so for arabic try to fallback to arial

src/root/views/preparedness.js
=> Missed one tabDetails on Preparedness

src/root/views/emergency.js
=> comment out add 3w activity button on emergency page

src/root/components/country/preparedness-overview.js
=> Removed unnecessary useEffect

src/root/lang.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1638#issuecomment-756393472
cc @batpad
=> Fix Open Surge Positions title text

src/root/views/emergency.js
Uses the correct variable for the field report count taking into account permissions.
=> Fix #1504 - Field report count

src/root/components/header.js, src/root/components/mobile-header.js
Ref.: https://github.com/IFRCGo/go-frontend/pull/1805
=> [Staging] Links changed to direct to the new KoBo urls

src/root/components/header.js, src/root/components/mobile-header.js
- COVID-19 Indicator Tracking - new url: https://eenew.ifrc.org/single/y300V3lY?returnURL=https://go.ifrc.org/emergencies/3972#actions
- COVID-19 NS Financial Overview - new url: https://eenew.ifrc.org/single/VmcTHDMh?returnURL=https://go.ifrc.org/emergencies/3972#actions
Ref.: https://github.com/IFRCGo/go-frontend/issues/1796
=> Release v4.5.2

src/root/components/map/home-map/explanation-bubble.js, src/root/components/map/home-map/factory/marker-layer-stylesheet-factory.js, src/root/lang.js, src/root/utils/appeal-type-constants.js, src/styles/home/_global.scss
Ref.: https://github.com/IFRCGo/go-frontend/issues/1798
- Add new EAP AppealType to list filters and map
=> Add EAP Appeal type to list filter and map

src/root/components/map/home-map/explanation-bubble.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1798
=> Move EAP between DREF and Movement

src/root/components/footer.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1809
=> Fix typo in footer link

src/root/components/form-elements/checkbox-group-actions.js, src/root/lang.js, src/root/views/field-report-form/cmp-action-checkboxes.js, src/root/views/field-report-form/data-utils.js, src/root/views/field-report-form/index.js, src/styles/field-report/_form.scss, src/styles/global/_folds.scss, src/styles/global/_tooltip.scss
Ref.: https://github.com/IFRCGo/go-frontend/issues/1797
- Add notes textareas to Actions' categories
- Change some of the placeholder/description/label texts
- Fix some of the styling
- Grouped External Partners and Supported Activities dropdowns into 1 line
cc @batpad @kamicut
=> Actions notes fields, changes

src/root/lang.js, src/root/utils/field-report-constants.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1797
=> Fix new cases, deaths labels

src/root/actions/index.js, src/root/reducers/index.js, src/root/reducers/main_contacts.js, src/root/views/about.js, src/styles/about/_global.scss
Ref.: https://github.com/IFRCGo/go-frontend/issues/1820
Backend-PR required: https://github.com/IFRCGo/go-api/pull/1006
- Add action, reducer of `mainContacts`
- Add contacts onto the About page
- Refactor About component to use React-hooks
=> About page contacts to come from the API

src/root/lang.js, src/root/views/field-report-form/index.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1797#issuecomment-779250686
=> Remove Source of figures description

src/root/actions/index.js, src/root/reducers/index.js, src/root/reducers/lang-all.js, src/root/selectors/index.js, src/root/views/TranslationDashboard/index.js
Requires: https://github.com/IFRCGo/go-api/pull/1017
- Add "Export ALL strings" functionality
=> Add option to export all lang-strings

src/root/selectors/index.js
For: https://github.com/IFRCGo/go-frontend/pull/1832
=> Fix for linter

src/root/views/field-report.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1797
=> Added new fields to the FR display view

src/root/components/footer.js, src/root/config.js, src/root/views/ThreeW/table.js, src/root/views/emergency.js
Changes `href` links to use adminUrl. I’m not sure about what the default should be for non production links so I added the staging site, is that correct @batpad?
=> change links to admin pages to use adminUrl

src/root/components/map/home-map/factory/marker-layer-stylesheet-factory.js, src/styles/home/_global.scss
Address https://github.com/IFRCGo/go-frontend/issues/1202#issuecomment-785016473
cc @jhenshall @batpad @GregoryHorvath
=> revise map marker colours and match legend

src/root/lang.js
Address https://github.com/IFRCGo/go-frontend/issues/1811
cc @jhenshall @batpad @GregoryHorvath
=> operations popup people affected -> people targeted

src/root/views/region.js
Addresses https://github.com/IFRCGo/go-frontend/issues/1643#issuecomment-788602144
cc @jhenshall @batpad @GregoryHorvath
=> region page slider should only show independent countries

src/root/utils/get-new-map.js
addresses https://github.com/IFRCGo/go-frontend/issues/1815
cc @jhenshall
=> enable map attribution

src/root/components/map/home-map/explanation-bubble.js
Addresses https://github.com/IFRCGo/go-frontend/issues/1835
cc @jhenshall @batpad
=> remove movement bubble from home page map

src/root/components/per-forms/per-overview.js
Req. came from an email from Stephanie
=> Add description for method_asmt_used

CHANGELOG.md, package.json, src/root/views/RegionalThreeW/ns-activities-filters.js
Hotfix for #1851 
Thanks @GregoryHorvath 
This includes a single change that should fix the 3w tab on the region page crashing.
=> Add nullcheck for countriesByIso

src/root/views/Covid19ThreeWSankey/Filters.js
This should fix our remaining issue with `countriesByIso`
=> Nullcheck for ISO at Sankey filters too

src/root/components/per-forms/per-overview.js
Req. backend PR: https://github.com/IFRCGo/go-api/pull/1027
- Made Assessment number editable, but it also updates if the selected Country already has assessments
=> PER assessment number to be editable

src/root/selectors/index.js, src/root/utils/field-report-constants.js, src/root/views/ThreeW/project-form.js
Refs #1845 
cc @jhenshall @geohacker
=> Refs #1845, fixes to dropdown logic for independent countries

src/root/components/form-elements/select-input.js, src/root/views/RegionalThreeW/ns-activities-filters.js, src/root/views/ThreeW/project-form.js, src/root/views/field-report-form/index.js
Related to: https://github.com/IFRCGo/go-frontend/issues/1891
=> Fix usage for react-select multi

src/root/utils/constants.js
Addresses 3w: Unify user roles to match rest of Go IFRCGo/go-frontend#1312 
Synced the label with backend https://github.com/IFRCGo/go-api/blob/develop/api/models.py#L281-L291.
=> Update project visibility label.

src/root/utils/eru-types.js
Added:
'9': 'Water Supply and rehabilitation',
'10': 'Household Water Treatment and safe storage',
'11': 'Cholera Case management at Community level',
'12': 'Safe and Dignified Burials',
'13': 'Community Based Surveillance',
'14': 'Base Camp – S',
'15': 'Base Camp – M',
'16': 'Base Camp – L'
=> Adding new ERU types

src/root/components/AlertContainer/index.tsx, src/root/components/Checklist/index.tsx, src/root/components/Container/index.tsx, src/root/components/RadioInput/index.tsx, src/root/components/system-alerts.js, src/root/views/FieldReportForm/ResponseFields/index.tsx
Reverts commit to change case names of imports.
@frozenhelium to work on a proper solution to this.
cc @vdeak
=> Revert "imports - case sensitive component names"

src/root/utils/restRequest/go.ts
* Fixes issue with POST request on field report form for Spanish language
* Add enforceEnglish option on requests
=> Enforce english language on POST, PATCH request

src/root/components/emergencies/overview.js, src/root/lang.js, src/root/views/FieldReportForm/index.tsx, src/root/views/ThreeWEdit/index.tsx, src/root/views/emergency.js, src/styles/emergency/_global.scss
- Add Links section
- Add Fetaured Documents section
- Clean up UI for response documents
Depends on: https://github.com/IFRCGo/go-api/pull/1120
Related to #1950
=> Add covid page related updates in emergency page

src/root/lang.js
Oops, had left some commented code in lang.js, this PR just cleans that up.
cc @frozenhelium
=> remove commented code from lang.js

src/root/components/country/preparedness-overview.js
=> Show no data message on Preparedness tab

src/root/utils/utils.js
=> fix duration display for when days > 25

src/root/views/register.js
I needed to fix only 1 row, 
```
-          if (country.society_name && country.society_name !== 'ICRC') {
+          if (country.society_name && country.society_name !== 'ICRC' && country.independent) {
```
=> Filtering for independent countries to avoid repeated NS name listing

src/root/components/connected/alerts-table.js
Depends on: https://github.com/IFRCGo/go-api/pull/1155
Addresses https://github.com/IFRCGo/go-frontend/issues/1988
=> Show Country from SurgeAlert.country, not through event

src/root/views/about.js
Fixes https://github.com/IFRCGo/go-frontend/issues/1999
=> Change link to ifrcgo.org/go-user-library

src/root/components/connected/alerts-table.js
if (userNotLoggedIn) {... do not show surge alerts... }
=> Not showing surge alerts to anon users

src/root/utils/mergeDeployData.js
@willemarcel this just filters out ERUs that do not have a country for deployed_to - let me know if this looks okay
refs #2020
=> refs #2020 - filter out erus where deployed_to is null

src/root/views/emergency.js
=> Using state.event.aggregated.data instead of state.event.data

src/root/views/about.js
aboutReferenceCenters link fixed
=> Fix broken links towards ifrc.org

src/root/components/preparedness/preparedness-header.js
The country page related links should be fixed via database (via some api_country.url_ifrc updates).
=> Fixing broken links

src/root/components/SearchSelectInput/index.tsx, src/root/views/DrefApplicationForm/ActionsFields/index.tsx, src/root/views/DrefApplicationForm/DrefOverview/CopyFieldReportSection/index.tsx, src/root/views/DrefApplicationForm/DrefOverview/index.tsx, src/root/views/DrefApplicationForm/Response/index.tsx, src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefApplicationForm/useDrefFormOptions.ts
Fix validation for type_of_onset imminent
=> Fix validation issue on type Imminent

src/root/components/map/emergency-map.js
=> Country grey others darks

src/root/components/connected/alerts-table.js, src/root/components/connected/eru-table.js, src/root/components/connected/personnel-table.js
Also backend not-sending is happening with frontend hiding.
=> The alerts person-name (only) is hidden for anon users

src/root/components/connected/alerts-table.js, src/root/lang.js, src/root/views/deployments.js, src/root/views/emergencies.js
https://github.com/IFRCGo/go-frontend/issues/2115
=> Feature/surge stood-down

src/root/components/deployments/personnel-by-event-table.js
Solves https://github.com/IFRCGo/go-frontend/issues/2131
=> Instead of return null we give a noDataMessage at ORRDbE

package.json, src/root/components/Svg/index.tsx, src/root/components/Svg/styles.module.scss, src/root/views/Surge/operational-timeline.js, yarn.lock
=> Adding svg injector

src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefApplicationForm/useDrefFormOptions.ts
Fix validation error on Person Targeted and budget
=> Fix validation error

src/root/components/map/emergency-map.js
@szabozoltan69 could you try and see if this fixes the issue for you as I am unable to reproduce locally
refs #2172
=> add setTimeout to try and fix map export issue

src/root/components/DrefPdfExport/index.tsx, src/root/components/DrefPdfExport/pdfStyles.ts
=> fix minor dref pdf feedbacks

src/root/views/emergency.js
Solves https://github.com/IFRCGo/go-frontend/issues/2057 tab part
=> Do not show surge tab if 0-0

.circleci/config.yml, src/root/Multiplexer/index.js, src/root/components/RouterTabs/index.js, src/root/views/Surge/catalogue-of-surge-services-subpage.js, src/root/views/Surge/catalogue-of-surge-services.js, src/root/views/deployments.js
Very WIP - change tabs to use React routes to manage routing, so that we can handle nested URL state when there is navigation within tabs.
=> Move tabs to using React Routes

src/root/views/Surge/catalogue-of-surge-services.js
Fixes back button behaviour on catalogue of surge services subpages
cc @tovari @szabozoltan69
=> fix back button to take users one level back from catalogue of services subpages

src/root/lang.js, src/root/views/Surge/contentData/operation-timeline-content.js, src/root/views/emergency.js, src/root/views/register.js
registerJustify, this.state.hasSurgeAlerts, smcctoolkit
=> 3 quick fixes

src/root/views/Country/index.js
Solves https://github.com/IFRCGo/go-frontend/issues/2212
=> Redirect region semi-countries to regions

src/root/views/FieldReportForm/ContextFields/index.tsx
Solves https://github.com/IFRCGo/go-frontend/issues/2216
=> FR summary maxLength = 100

src/root/views/emergency.js
Solves https://github.com/IFRCGo/go-frontend/issues/2209
=> Funding: 0 should be shown

src/root/components/connected/personnel-table.js
=> make consistent the string that shows for undefined name, refs #2261

cypress-test.sh, package.json
You need to install cypress for yourself, will not be installed via yarn install.
=> CyPress into package.json

src/root/Multiplexer/index.js, src/root/components/mobile-navbar.js, src/root/components/navbar.js, src/root/views/Country/index.js, src/root/views/account.js, src/root/views/emergencies.js, src/root/views/emergency.js, src/root/views/region.js
- Enable New DREF and New Flash update in navbar dropdown and mobile
navbar
- Add back regional risk tab to regions page
- Add back country risk tab to country page
- Enable routes for DREF and Flash update
- Add back my dref application tab to accounts page
=> Unhide temporarily hidden features

src/root/components/ThreeWForm/useThreeWOptions.ts
Fix for https://github.com/IFRCGo/go-frontend/issues/1934
Tested locally that this works.
@frozenhelium will be great to get a 👍 from you here if this looks okay, not sure if there's a better way to check for `null OR true` .
cc @szabozoltan69 @tovari
=> Include IFRC / ICRC in Reporting NS in 3w form

src/root/components/EmergencyThreeWForm/index.tsx, src/root/components/EmergencyThreeWForm/useEmergencyThreeWOptions.ts, src/root/views/Emergency/index.js
- Only show Activities tab in emergency page if it has activity
=> Allow any country to be selected in emergency 3W form

src/root/views/FieldReportForm/ResponseFields/index.tsx, src/root/views/FieldReportForm/common.tsx, src/root/views/FieldReportForm/index.tsx, src/root/views/FieldReportForm/useFieldReportOptions.ts
A quick (first) solution to https://github.com/IFRCGo/go-api/issues/1397
=> FR vetting

src/root/components/EmergencyThreeWForm/index.tsx, src/root/components/EmergencyThreeWForm/useEmergencyThreeWOptions.ts, src/root/components/ThreeWForm/useThreeWOptions.ts, src/root/lang.js
Solves row Nr9 in https://github.com/IFRCGo/go-frontend/issues/2329 GSS
=> Also IFRC, ICRC in 3W NS list

CHANGELOG.md, src/root/components/KeyFigure/index.tsx, src/root/views/Emergency/Activities/index.tsx, src/root/views/Emergency/Activities/projectTableColumns.tsx
Instead of People reached - and some tooltip for it.
=> hotfix for keyfigure text correction

src/root/components/RichTextOutput/index.tsx, src/root/lang.js, src/root/views/FlashUpdateApplicationForm/Context/CountryProvinceInput/index.tsx, src/root/views/FlashUpdateApplicationForm/index.tsx
- Remove delete button for the first country (instead of disabling it)
in the Flash Update Form
- Change label of submit button from "Save" to "Submit" in the Flash
Update Form
- Update RichTextOutput to support the text-align attribute
=> Perform few UI enhancements in the Flash Update

src/root/components/RichTextArea/index.tsx, src/root/components/ThreeWDetails/index.tsx
No centering in 3w project description.
=> Rich Text experience busting

src/root/components/RichTextArea/index.tsx, src/root/components/ThreeWDetails/index.tsx, src/root/config.js
To avoid "This domain is not registered with Tiny Cloud..." message and to have a nice rich-text editing interface.
=> tinymce key fix with some addons

src/root/components/RichTextArea/index.tsx, src/root/components/ThreeWForm/index.tsx, src/root/views/FieldReportForm/SituationFields/index.tsx, src/root/views/FlashUpdateApplicationForm/Context/index.tsx
According to https://www.tiny.cloud/blog/tinymce-placeholder-text
=> Placeholder to TinyMCE

src/root/Multiplexer/index.js, src/root/components/mobile-navbar.js, src/root/components/navbar.js, src/root/utils/common.ts, src/root/views/AllFlashUpdates/index.tsx, src/root/views/FlashUpdateApplicationForm/index.tsx, src/root/views/FlashUpdateReport/index.tsx, src/root/views/emergencies.js
- Make flash update only available to IFRC user
=> Flash update permission

src/root/components/emergencies/overview.js
For https://github.com/IFRCGo/go-frontend/issues/2307
=> NS Requests International Assistance - on emergencies

.circleci/config.yml, src/root/components/footer.js, src/root/lang.js, src/root/views/app.js
Also a circleCI simplification
=> Hide top banner, use dynamic copyright date

src/root/components/navbar.js, src/root/utils/utils.js
Linear, comparable permission level order:
```
2IFRC                      9
4IFRC_NS                   8
1MEMBERSHIP (logged in)    7
3PUBLIC                    6
```
=> Show only permitted search result records

src/root/views/per-assessment.js
=> formState object can be missing

src/root/components/RichTextOutput/index.tsx
Refers to https://github.com/IFRCGo/go-frontend/issues/2177
Also refers to https://github.com/IFRCGo/go-frontend/issues/2133
=> Adding more HTML tags for TinyMCE

src/root/views/TranslationDashboard/index.js, src/root/views/TranslationDashboard/styles.module.scss
Filter out empty language string before sending to server
=> Handle empty language values

src/root/views/TranslationDashboard/index.js, src/root/views/TranslationDashboard/styles.module.scss
Refers to https://github.com/IFRCGo/go-frontend/pull/2434#issuecomment-1208888828
=> Handl empty language values

src/root/actions/index.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2440
=> Setting more limits for PER form lists

src/root/components/EmergencyThreeWForm/EmergencyEventInput/index.tsx
Refers to https://github.com/IFRCGo/go-frontend/issues/2446
=> Response Activity related Events

src/root/views/Emergency/Activities/Filters/index.tsx, src/root/views/Emergency/Activities/useProjectStats.ts
Refers to https://github.com/IFRCGo/go-frontend/issues/2461
=> districts_details in Activities

src/root/components/ThreeWForm/AnnualSplitInput/index.tsx, src/root/components/ThreeWForm/useThreeWOptions.ts
Annual split magic
.../three-w/2783 - a splitted project on staging
.../three-w/1446 - a non-splitted project on staging
=> Calculating and conditionally-disabling splitted totals

CHANGELOG.md, package.json, src/root/components/DrefPdfDocument/NationalSocietyOutput/index.tsx, src/root/components/DrefPdfDocument/PreviousOperationOutput/index.tsx, src/root/components/DrefPdfDocument/RiskAndSecurityOutput/index.tsx, src/root/components/ThreeWForm/index.tsx
- Bump version and add changelog for hotfix
=> Fix overlapping of text in dref export

src/root/components/BasicModal/styles.module.scss, src/root/utils/restRequest/go.ts, src/root/views/DrefApplicationForm/ObsoletePayloadResolutionModal/index.tsx, src/root/views/DrefApplicationForm/common.tsx, src/root/views/DrefApplicationForm/index.tsx
Depends on: https://github.com/IFRCGo/go-api/pull/1554
=> Implement optimistic locking in DREF form

src/root/components/export-button-component.js, src/root/hooks/useExportButton.js, src/root/lang.js
@frozenhelium @tnagorra Please advice me a better solution for title assignment than this renderToStaticMarkup + replace. (Without importing the full lang "strings", of course.)
=> Tooltips for CSV exports

src/root/views/account.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2545
Also a database cleanup is needed (delete duplicates).
=> Fix for region, disasterType and country subscriptions

src/root/lang.js, src/root/views/DrefApplicationForm/ActionsFields/index.tsx, src/root/views/DrefApplicationForm/EventDetails/index.tsx, src/root/views/DrefApplicationForm/Response/InterventionInput/index.tsx, src/root/views/DrefApplicationForm/Response/index.tsx, src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefOperationalUpdateForm/EventDetails/index.tsx, src/root/views/DrefOperationalUpdateForm/Needs/index.tsx, src/root/views/DrefOperationalUpdateForm/Operation/index.tsx, src/root/views/DrefOperationalUpdateForm/Overview/index.tsx, src/root/views/DrefOperationalUpdateForm/index.tsx, src/root/views/DrefOperationalUpdateForm/useDrefOperationalUpdateOptions.ts, src/root/views/FinalReportForm/Operation/index.tsx
Addresses https://github.com/IFRCGo/go-frontend/issues/2418
=> DREF Ops. update improvements

src/root/Multiplexer/index.js, src/root/components/DropdownMenuItem/index.tsx, src/root/components/form-elements/radio-group.js, src/root/components/map/main-map.js, src/root/views/GlobalThreeW/index.tsx, src/root/views/region.js
@batpad @frozenhelium @tnagorra – if you have better solution, please tell me.
Refers to https://github.com/IFRCGo/go-frontend/issues/2555
=> Quick fix for 3w regions blank page

src/root/components/OperationalUpdatePdfDocument/PlannedInterventionOutput/index.tsx, src/root/lang.js, src/root/utils/pdf/pdfStyles.ts, src/root/views/DrefApplicationForm/useDrefFormOptions.ts, src/root/views/DrefOperationalUpdateForm/common.tsx, src/root/views/DrefOperationalUpdateForm/index.tsx, src/root/views/DrefOperationalUpdateForm/useDrefOperationalUpdateOptions.ts
##changes #2418 
- Remove priority actions from ops update export 
- Fix Planned intervention actual field update 
- Add the actual field in export and update the styling
=> Fix operational update changes

src/root/lang.js, src/root/views/DrefApplicationForm/common.tsx, src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefOperationalUpdateForm/Operation/index.tsx, src/root/views/DrefOperationalUpdateForm/common.tsx, src/root/views/DrefOperationalUpdateForm/index.tsx, src/root/views/DrefOperationalUpdateForm/useDrefOperationalUpdateOptions.ts
Following fields were not being saved
- Summary of change
- Progress toward outcome (Planned intervention)
=> Fix ops update not saving some fields

src/root/lang.js, src/root/views/FinalReportForm/Submission/index.tsx
##changes
- Fix the label name in the timeframe section.
=> Fix final report fields name

src/root/components/OperationalUpdatePdfDocument/PlannedInterventionOutput/index.tsx
- Fix actual field in operational update export
=> Fix Ops update export

src/root/components/OperationalUpdatePdfDocument/PlannedInterventionOutput/index.tsx
- List of activities field removed from PI section export
=> Remove fields in Ops update export

src/root/views/DrefOperationalUpdateForm/index.tsx
- show assessment report file icon
=> Fix ops update

src/root/views/FinalReportForm/Overview/index.tsx, src/root/views/FinalReportForm/common.tsx, src/root/views/FinalReportForm/index.tsx, src/root/views/FinalReportForm/useDreFinalReportOptions.ts
- Remove is assessment report question
=> Fix final report

src/root/lang.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2579
=> Appeal Code instead of MDR Code – used on 2 pages

src/root/components/FinalReportPdfDocument/NationalSocietyOutput/index.tsx, src/root/components/FinalReportPdfDocument/PlannedInterventionOutput/index.tsx, src/root/views/FinalReportForm/Needs/index.tsx, src/root/views/FinalReportForm/Operation/InterventionInput/index.tsx, src/root/views/FinalReportForm/Operation/InterventionInput/styles.module.scss, src/root/views/FinalReportForm/Operation/styles.module.scss, src/root/views/FinalReportForm/useDreFinalReportOptions.ts
- issues: #2556 
- Remove and add fields to the final report form and export.
=> Fix issues final report

src/root/components/FinalReportPdfDocument/EventDescriptionOutput/index.tsx, src/root/components/FinalReportPdfDocument/PlannedInterventionOutput/index.tsx, src/root/components/FinalReportPdfDocument/index.tsx, src/root/components/OperationalUpdatePdfDocument/EventDescriptionOutput/index.tsx, src/root/components/OperationalUpdatePdfDocument/PlannedInterventionOutput/index.tsx, src/root/views/DrefOperationalUpdateForm/EventDetails/index.tsx, src/root/views/FinalReportForm/EventDetails/index.tsx
Addresses issues (#2556)
* Add fields in the final report export implementation section
* Rearrange the implementation section in the final report export 
* Fix event description title in ops update and final report export
=> Fix Final report changes

src/root/components/RadioInput/styles.module.scss, src/root/views/FieldReportForm/ContextFields/index.tsx
Related to: https://github.com/IFRCGo/go-frontend/issues/2581
=> Fix radio input clear button for rtl

src/root/views/FinalReportForm/useDreFinalReportOptions.ts
* Fix save on sharing users in the final report
=> Fix final report shared users

src/root/components/connected/alerts-table.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2612
=> Surge Alert table without 30 days limit

src/root/components/Card/styles.module.scss, src/root/components/Container/styles.module.scss, src/root/components/GoMapDisclaimer/index.tsx, src/root/components/GoMapDisclaimer/styles.module.scss, src/root/components/Link/index.tsx, src/root/components/Link/styles.module.scss, src/root/components/RiskImminentEventMap/index.tsx, src/root/components/RiskImminentEventMap/styles.module.scss, src/root/components/Table/predefinedColumns.ts, src/root/utils/get-new-map.js, src/root/utils/map.ts, src/root/views/AllFlashUpdates/flashUpdateTableColumns.ts, src/root/views/Country/ThreeW/InCountryProjects/styles.module.scss, src/root/views/Emergency/Activities/ActivityMap/index.tsx, src/root/views/Emergency/Activities/ActivityMap/styles.module.scss, src/root/views/RegionalRiskWatch/SeasonalRisk/Map/index.tsx, src/root/views/RegionalRiskWatch/SeasonalRisk/Map/styles.module.scss
* Add Link Component
* Improve styling for all flash update table
* Add disclaimer to risk maps
* Add disclaimer to emergency activities map
* Move mapbox attribution inside disclaimer pop-up
=> Add UN CODs link in Map Disclaimer

src/root/views/DrefApplicationForm/DrefOverview/ImageWithCaptionInput/styles.module.scss, src/root/views/DrefOperationalUpdateForm/index.tsx, src/root/views/DrefOperationalUpdateForm/useDrefOperationalUpdateOptions.ts
* Improve total_operation_timeframe and number_of_targeted_population fields condition on null.
=> Fix Operational Update

src/root/components/DrefApplicationList/index.tsx, src/root/components/per-forms/per-account.js
Refers to https://github.com/IFRCGo/go-frontend/issues/1869
=> Using the same country dropdown in PER as in DREF

src/root/components/connected/alerts-table.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2612
=> Surge Alerts list with 30 days limit. Excluding closed ones.

src/root/lang.js, src/root/views/about.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2632
=> GO Workplan yearly update

src/root/views/DrefOperationalUpdateForm/index.tsx, src/root/views/DrefOperationalUpdateForm/styles.module.scss, src/root/views/DrefOperationalUpdateForm/useDrefOperationalUpdateOptions.ts
* Fix DREF user permission
* Fix operational update timeframe validation
=> Fix - DREF application issues

config/webpack.config.js, package.json, src/root/components/footer.js, src/root/config.js, yarn.lock
Refers to https://github.com/IFRCGo/go-frontend/issues/2490
=> Show git commit hash in footer

config/webpack.config.js
=> Fix for ERR_OSSL_EVP_UNSUPPORTED

.gitignore, package.json, src/root/views/RegionalRiskWatch/SeasonalRisk/CountryRiskBarChart/index.tsx, src/root/views/RegionalRiskWatch/SeasonalRisk/CountryRiskBarChart/styles.module.scss, yarn.lock
* Fix the sidebar tooltip according to the react-tooltip new version
=> Fix seasonal risk watch styling

config/webpack.config.js, docker-compose.yml, src/root/components/footer.js, src/root/config.js
I could not solve it via ReactTooltip. If you have a better way, let me know. This way I used simply the "title".
@frozenhelium ?
=> Use gitRevision plugin to show version and git hash

src/root/views/RegionalRiskWatch/SeasonalRisk/CountryRiskBarChart/index.tsx, src/root/views/RegionalRiskWatch/SeasonalRisk/Map/Choropleth/index.tsx
* Filter out seasonal risk watch hazard data with zero value
=> Fix seasonal risk watch tooltip

src/root/components/ThreeWDetails/index.tsx
Refers to https://github.com/IFRCGo/go-api/issues/1695
=> Three-w project_country instead of reporting_ns_country

CHANGELOG.md, package.json, src/root/components/DrefPdfDocument/PreviousOperationOutput/index.tsx
@szabozoltan69 Please deploy this to the production! Thanks in advance!
=> Hotfix DREF export empty string

src/root/lang.js, src/root/views/GlobalThreeW/index.tsx, src/root/views/GlobalThreeW/styles.module.scss
Refers to https://github.com/IFRCGo/go-api/issues/1704
=> PPP dashboard integration to the 3W page

src/root/views/FieldReportForm/ContextFields/index.tsx
Refers to https://github.com/IFRCGo/go-frontend/issues/2675
=> Fix JSX comment

CHANGELOG.md, package.json, src/root/views/FieldReportForm/ContextFields/index.tsx
@szabozoltan69 lets merge and deploy this to the prod. Thanks in advance! :)
=> Hotfix Field Report Form comment

src/root/components/MapEaseTo/index.tsx, src/root/components/RiskImminentEventMap/ADAMEventMap/MapFooter/styles.module.scss, src/root/components/RiskImminentEventMap/ADAMEventMap/PointDetails/index.tsx, src/root/components/RiskImminentEventMap/ADAMEventMap/PointDetails/styles.module.scss, src/root/components/RiskImminentEventMap/ADAMEventMap/index.tsx, src/root/types/risk.ts, src/root/utils/map.ts
* fix adam mapbox empty hazard
=> Fix adam empty data

src/root/components/OperationalUpdateExport/index.tsx, src/root/utils/pdf/pdfStyles.ts, src/root/views/DrefApplicationForm/common.tsx, src/root/views/DrefOpPdfPreview/index.tsx, src/root/views/FinalReportForm/EventDetails/index.tsx, src/root/views/FinalReportForm/Operation/index.tsx
* remove duplicate variable
* fix type error in ops update
=> Fix DREF duplicate

src/root/components/DrefPdfDocument/PreviousOperationOutput/index.tsx, src/root/components/DrefPdfDocument/index.tsx, src/root/components/FinalReportPdfDocument/EssentialInformationOutput/index.tsx, src/root/components/FinalReportPdfDocument/EventDescriptionOutput/index.tsx, src/root/components/FinalReportPdfDocument/NeedIdentifiedOutput/index.tsx, src/root/components/FinalReportPdfDocument/TargetedPopulationOutput/index.tsx, src/root/components/FinalReportPdfDocument/index.tsx, src/root/utils/pdf/pdfStyles.ts, src/root/views/DrefApplicationForm/DrefOverview/index.tsx, src/root/views/DrefApplicationForm/EventDetails/index.tsx, src/root/views/DrefApplicationForm/common.tsx, src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefApplicationForm/useDrefFormOptions.ts, src/root/views/FinalReportForm/EventDetails/index.tsx, src/root/views/FinalReportForm/Operation/index.tsx, src/root/views/FinalReportForm/Overview/index.tsx, src/root/views/FinalReportForm/index.tsx
* Fix DREF export
* Change variable request according to server
* Add new dref type on Final report
* Fix final report export
=> Fix DREF and Final Report

src/root/components/RiskImminentEventMap/ADAMEventMap/MapFooter/index.tsx, src/root/components/RiskImminentEventMap/ADAMEventMap/PointDetails/index.tsx, src/root/components/RiskImminentEventMap/ADAMEventMap/index.tsx, src/root/components/RiskImminentEventMap/PDCEventMap/MapFooter/index.tsx, src/root/components/RiskImminentEventMap/PDCEventMap/MapFooter/styles.module.scss, src/root/components/RiskImminentEventMap/PDCEventMap/index.tsx, src/root/components/RiskImminentEventMap/PDCEventMap/styles.module.scss
* Fix hazard point color according to type in PDC and ADAM events.
* Add footprints color same as hazard type.
* Add a footer component for PDC events.
=> Fix Imminent Risk Watch

src/root/components/RiskImminentEventMap/ADAMEventMap/PointDetails/index.tsx, src/root/views/Search/EmergencyTable/index.tsx
* Add hectares unit in flood area
* Remove unused variable form search
=> Fix Adam Risk Watch

src/root/views/Surge/contentData/catalogue-of-surge-services-content.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2701
=> Aligning CoS Role Profiles in Communications section

src/root/views/Search/EmergencyTable/index.tsx, src/styles/global/_cards.scss, src/styles/global/_states.scss, src/styles/settings/_variables.scss
=> Add crisis dot colors

src/root/components/RiskImminentEventMap/ADAMEventMap/index.tsx, src/root/components/RiskImminentEventMap/MapFooter/index.tsx, src/root/components/RiskImminentEventMap/PDCEventMap/index.tsx, src/root/types/risk.ts, src/root/utils/risk.ts, src/root/views/Country/RiskWatch/SeasonalRisk/RiskBarChart/index.tsx
Fixes: #2707
- Add wlidfire in PDCmap
=> Add wlidfire event data

src/root/components/DrefApplicationList/index.tsx, src/root/components/FinalReportExport/index.tsx, src/root/lang.js, src/root/views/DrefApplicationForm/DrefOverview/index.tsx, src/root/views/DrefApplicationForm/EventDetails/index.tsx, src/root/views/DrefApplicationForm/Submission/index.tsx, src/root/views/DrefApplicationForm/common.tsx, src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefApplicationForm/useDrefFormOptions.ts, src/root/views/DrefOperationalUpdateForm/EventDetails/index.tsx, src/root/views/DrefOperationalUpdateForm/Overview/index.tsx, src/root/views/DrefOperationalUpdateForm/Submission/index.tsx, src/root/views/DrefOperationalUpdateForm/common.tsx, src/root/views/DrefOperationalUpdateForm/index.tsx, src/root/views/DrefOperationalUpdateForm/useDrefOperationalUpdateOptions.ts, src/root/views/FinalReportForm/useDreFinalReportOptions.ts
=> Add loan form validation

src/root/components/DrefApplicationList/index.tsx, src/root/views/Country/RiskWatch/ImminentEvents/index.tsx, src/root/views/RegionalRiskWatch/ImminentEvents/index.tsx
* Fix footer and source type in country risk watch
=> Fix Imminent  Risk Watch

src/root/components/DrefPdfDocument/HeadingOutput/index.tsx, src/root/components/EmergencyThreeWForm/SectorInput/ActivityInput/index.tsx, src/root/components/EmergencyThreeWForm/SectorInput/CustomActivityInput/index.tsx, src/root/components/EmergencyThreeWForm/SectorInput/index.tsx, src/root/components/EmergencyThreeWForm/index.tsx, src/root/utils/pdf/pdfStyles.ts, src/root/views/Country/RiskWatch/SeasonalRisk/ReturnPeriodTable/index.tsx, src/root/views/Country/RiskWatch/SeasonalRisk/index.tsx, src/root/views/DrefApplicationForm/ActionsFields/index.tsx, src/root/views/DrefApplicationForm/DrefOverview/index.tsx, src/root/views/DrefApplicationForm/Response/index.tsx, src/root/views/DrefOperationalUpdateForm/Needs/index.tsx, src/root/views/DrefOperationalUpdateForm/Operation/index.tsx, src/root/views/DrefOperationalUpdateForm/Overview/index.tsx, src/root/views/DrefOperationalUpdateForm/Submission/index.tsx, src/root/views/Emergency/Activities/index.tsx, src/root/views/FinalReportForm/Needs/index.tsx, src/root/views/FinalReportForm/Operation/index.tsx, src/root/views/FinalReportForm/Overview/index.tsx, src/root/views/FlashUpdateApplicationForm/Context/index.tsx, src/root/views/NewThreeW/index.tsx, src/root/views/RegionalRiskWatch/SeasonalRisk/index.tsx
* Fix dref export title width
* Fix and remove overflow properties from the container component
=> Fix Dref Export

CHANGELOG.md, package.json, src/root/lang.js, src/root/views/Surge/contentData/catalogue-of-surge-services-content.js, src/root/views/Surge/contentData/map-pdf-to-sharepoint.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2735
=> Increase version to v6.5.5

src/root/components/EmergencyThreeWForm/index.tsx, src/root/components/ThreeWForm/useThreeWOptions.ts
Refers to https://github.com/IFRCGo/go-api/issues/1755
=> Non-mandatory districts in (emergency)projects

src/root/components/ThreeWForm/useThreeWOptions.ts, src/root/views/Emergency/Activities/index.tsx
Refers to https://github.com/IFRCGo/go-api/issues/1755
=> Using only needed districts in country

src/root/views/Country/ThreeW/InCountryProjects/index.tsx
Refers to https://github.com/IFRCGo/go-api/issues/1755
=> Optional districts display on country 3w map

src/root/utils/constants.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2665
=> New sectors temporary copy from backend

CHANGELOG.md, package.json, src/root/views/about.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2750
=> Increase version to v6.5.6

src/root/lang.js, src/root/views/Emergency/index.js
Refers to https://github.com/IFRCGo/go-api/issues/1754
=> More columns to AppealDoc listing

src/root/components/RiskImminentEventMap/ADAMEventMap/PointDetails/index.tsx, src/root/components/RiskImminentEventMap/ADAMEventMap/index.tsx, src/root/components/RiskImminentEventMap/PDCEventMap/PointDetails/index.tsx, src/root/views/RegionalRiskWatch/ImminentEvents/index.tsx
* Add function to round the population data from decimal.
=> Fix Risk Watch Population Data

src/root/views/GoUI/components/Button/RawButton/index.tsx, src/root/views/GoUI/components/Button/RawButton/styles.module.scss, src/root/views/GoUI/components/Button/index.tsx, src/root/views/GoUI/components/Button/styles.module.scss, src/root/views/GoUI/components/DropdownMenu/DropdownMenuItem/index.tsx, src/root/views/GoUI/components/DropdownMenu/DropdownMenuItem/styles.module.scss, src/root/views/GoUI/components/DropdownMenu/index.tsx, src/root/views/GoUI/components/DropdownMenu/styles.module.scss, src/root/views/GoUI/components/RawButton/index.tsx, src/root/views/GoUI/components/RawButton/styles.module.scss, src/root/views/GoUI/examples/DropdownExample/index.tsx, src/root/views/GoUI/examples/DropdownExample/styles.module.scss, src/root/views/GoUI/examples/OverlayExample/index.tsx, src/root/views/GoUI/examples/OverlayExample/styles.module.scss, src/root/views/GoUI/hooks/index.tsx, src/root/views/GoUI/index.tsx, src/root/views/GoUI/styles.module.scss
- Task: https://github.com/toggle-corp/ifrc-go-meta/issues/100#issue-1684783155
- Add a dropdown component that can be used for making unique selectors
=> Add dropdown component for new UI elements

src/root/views/GoUI/components/InputContainer/index.tsx, src/root/views/GoUI/components/InputContainer/styles.module.scss, src/root/views/GoUI/components/InputError/index.tsx, src/root/views/GoUI/components/InputError/styles.module.scss, src/root/views/GoUI/components/InputLabel/index.tsx, src/root/views/GoUI/components/InputLabel/styles.module.scss, src/root/views/GoUI/components/InputSection/index.tsx, src/root/views/GoUI/components/InputSection/styles.module.scss, src/root/views/GoUI/components/RawInput/index.tsx, src/root/views/GoUI/components/RawInput/styles.module.scss, src/root/views/GoUI/components/RawTextArea/index.tsx, src/root/views/GoUI/components/RawTextArea/styles.module.scss, src/root/views/GoUI/components/TextArea/index.tsx, src/root/views/GoUI/examples/Headings/styles.module.scss, src/root/views/GoUI/examples/RawTextExample/index.tsx, src/root/views/GoUI/examples/RawTextExample/styles.module.scss, src/root/views/GoUI/examples/TextAreaExample/index.tsx, src/root/views/GoUI/examples/TextAreaExample/styles.module.scss, src/root/views/GoUI/index.tsx, src/root/views/GoUI/styles.module.scss
- Add core components which are vital for building the UI elements required for form sections
- Task (Input Error) : https://github.com/toggle-corp/ifrc-go-meta/issues/137#issue-1701394692
- Task (RawTextArea): https://github.com/toggle-corp/ifrc-go-meta/issues/148#issue-1701814719
- Task (TextArea): https://github.com/toggle-corp/ifrc-go-meta/issues/127#issue-1701328448
- Task (InputLabel): https://github.com/toggle-corp/ifrc-go-meta/issues/150#issue-1701882670
- Task (RawInput): https://github.com/toggle-corp/ifrc-go-meta/issues/135#issue-1701358125
- Task (InputContainer): https://github.com/toggle-corp/ifrc-go-meta/issues/136#issue-1701368471
- Task (InputSection): https://github.com/toggle-corp/ifrc-go-meta/issues/133#issue-1701340007
=> Add core components and text area component for form elements

src/root/views/GoUI/components/ButtonLikeLink/index.tsx, src/root/views/GoUI/components/DropdownMenu/DropdownMenuItem/index.tsx, src/root/views/GoUI/components/DropdownMenu/index.tsx, src/root/views/GoUI/components/Link/index.tsx, src/root/views/GoUI/components/Modal/index.tsx, src/root/views/GoUI/components/Tabs/Tab/index.tsx, src/root/views/GoUI/components/Tabs/TabList/index.tsx, src/root/views/GoUI/components/Tabs/index.tsx, src/root/views/GoUI/components/TextInput/index.tsx, src/root/views/GoUI/examples/Alerts/index.tsx, src/root/views/GoUI/examples/TextAreaExample/index.tsx, src/root/views/GoUI/examples/TextInputExample/index.tsx, src/root/views/GoUI/examples/TextInputExample/styles.module.scss, src/root/views/GoUI/index.tsx
- Add updates to the global styles and also add updates to the imported file paths
- Also add missing core components
- Add TextInput component which will be included in the form fields
- Task (TextInput): https://github.com/toggle-corp/ifrc-go-meta/issues/124#issue-1701325428
=> Add textInput component for form fields

src/root/views/GoUI/components/Checkbox/index.tsx, src/root/views/GoUI/components/DropdownMenu/DropdownMenuItem/styles.module.scss, src/root/views/GoUI/components/DropdownMenu/index.tsx, src/root/views/GoUI/components/InputContainer/index.tsx, src/root/views/GoUI/components/InputContainer/styles.module.scss, src/root/views/GoUI/components/InputError/index.tsx, src/root/views/GoUI/components/InputLabel/index.tsx, src/root/views/GoUI/components/InputSection/index.tsx, src/root/views/GoUI/components/NumberInput/index.tsx, src/root/views/GoUI/components/RawInput/index.tsx, src/root/views/GoUI/components/RawTextArea/index.tsx, src/root/views/GoUI/components/TextInput/index.tsx, src/root/views/GoUI/examples/Buttons/index.tsx, src/root/views/GoUI/examples/Cards/index.tsx, src/root/views/GoUI/examples/DropdownExample/index.tsx, src/root/views/GoUI/examples/Links/index.tsx, src/root/views/GoUI/examples/Modals/index.tsx, src/root/views/GoUI/examples/NumberInputExample/index.tsx, src/root/views/GoUI/examples/NumberInputExample/styles.module.scss, src/root/views/GoUI/examples/TextAreaExample/index.tsx, src/root/views/GoUI/index.tsx
- Add NumberInput that is used for inputs focused on taking numbers
- Task (NumberInput): https://github.com/toggle-corp/ifrc-go-meta/issues/127#issue-1701328448
=> Add numberInput component for number specific inputs

src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefOperationalUpdateForm/Overview/index.tsx, src/root/views/DrefOperationalUpdateForm/index.tsx, src/root/views/FinalReportForm/Overview/index.tsx, src/root/views/FinalReportForm/Submission/index.tsx, src/root/views/FinalReportForm/index.tsx
@szabozoltan69 Lets merge and send it to Prod as well.
=> Avoid crash when users detail is empty in dref

src/components/Alert/index.tsx, src/components/Breadcrumbs/index.tsx, src/components/Button/index.tsx, src/components/Checkbox/Checkmark/index.tsx, src/components/DropdownMenu/index.tsx, src/components/Header/index.tsx, src/components/InputError/index.tsx, src/components/Modal/index.tsx, src/views/GoUI/index.tsx
- Implement new icons designed for the UI components
- Also add fixes for the existing UI components
=> Add new icons and fixes to the UI elements

legacy/src/root/views/RegionalRiskWatch/SeasonalRisk/Map/Choropleth/index.tsx, package.json, src/App/index.tsx, src/views/Home/ActiveOperationMap/index.tsx, src/views/Home/ActiveOperationMap/utils.ts, yarn.lock
- Change color for hovered countries
- Show popup on click
- Shift text on the maps
- Update re-map
=> Add on click handler on map

src/root/components/RiskImminentEventMap/MapFooter/index.tsx, src/root/components/RiskImminentEventMap/MeteoSwissEvent/PointDetails/index.tsx, src/root/components/RiskImminentEventMap/MeteoSwissEvent/PointDetails/styles.module.scss, src/root/components/RiskImminentEventMap/MeteoSwissEvent/Sidebar/EventDetails/index.tsx, src/root/components/RiskImminentEventMap/MeteoSwissEvent/Sidebar/EventDetails/styles.module.scss, src/root/components/RiskImminentEventMap/MeteoSwissEvent/Sidebar/index.tsx, src/root/components/RiskImminentEventMap/MeteoSwissEvent/Sidebar/styles.module.scss, src/root/components/RiskImminentEventMap/MeteoSwissEvent/index.tsx, src/root/components/RiskImminentEventMap/MeteoSwissEvent/styles.module.scss, src/root/types/risk.ts, src/root/views/Country/RiskWatch/ImminentEvents/ImminentEventsMeteoSwiss/index.tsx, src/root/views/Country/RiskWatch/ImminentEvents/ImminentEventsMeteoSwiss/styles.module.scss, src/root/views/Country/RiskWatch/ImminentEvents/index.tsx, src/root/views/RegionalRiskWatch/ImminentEvents/ImminentEventsMeteoSwiss/index.tsx, src/root/views/RegionalRiskWatch/ImminentEvents/ImminentEventsMeteoSwiss/styles.module.scss, src/root/views/RegionalRiskWatch/ImminentEvents/index.tsx, src/root/views/RegionalRiskWatch/SeasonalRisk/CountryRiskBarChart/index.tsx, src/root/views/RegionalRiskWatch/SeasonalRisk/Map/index.tsx, src/root/views/RegionalRiskWatch/SeasonalRisk/index.tsx
* Feature: Add components required for meteoSwiss risk watch imminent.
* Fix seasonal risk bar chart tooltip multiple renders.
* Hide the map source select the footer icon.
=> Feature- MeteoSwiss Risk Watch

package.json, src/assets/env.js, src/root/components/DrefApplicationList/ActiveDrefTable/index.tsx, src/root/components/DrefApplicationList/CompletedDrefTable/index.tsx, src/root/components/DrefApplicationList/DrefApplicationTable/ShareUserModal/index.tsx, src/root/components/DrefApplicationList/DrefApplicationTable/ShareUserModal/styles.module.scss, src/root/components/DrefApplicationList/DrefApplicationTable/index.tsx, src/root/components/DrefApplicationList/index.tsx, src/root/components/DrefApplicationList/styles.module.scss, src/root/components/DrefApplicationList/useDrefApplicationListOptions.ts, src/root/components/DrefExportButton/index.tsx, src/root/components/ExpandButton/index.tsx, src/root/components/FinalReportExport/index.tsx, src/root/components/OperationalUpdateExport/index.tsx, src/root/components/Table/TableData/index.tsx, src/root/components/Table/TableData/styles.module.scss, src/root/components/Table/TableRow/index.tsx, src/root/components/Table/index.tsx, src/root/components/Table/predefinedColumns.ts, src/root/components/Table/useRowExpansion.tsx, src/root/lang.js, yarn.lock
* Fix expandable row table
* Add TableRow and TableData component
* Create different components and restructure the folder
* Add DREF active operation table
* Add completed DREF table
=> Feature - DREF Application Page

src/root/components/DrefApplicationList/ActiveDrefTable/index.tsx, src/root/components/DrefApplicationList/CompletedDrefTable/index.tsx, src/root/components/DrefApplicationList/DrefApplicationTable/ShareUserModal/index.tsx, src/root/components/DrefApplicationList/DrefApplicationTable/index.tsx, src/root/components/DrefApplicationList/index.tsx, src/root/components/DrefApplicationList/styles.module.scss, src/root/components/DrefApplicationList/useDrefApplicationListOptions.ts, src/root/index.js
* Fix pagination
* Fix other string names
* Add appeal code filter
* Add disaster type filter
* Show status
* Share user by email
=> Fix - DREF application account page

src/root/components/DrefApplicationList/CompletedDrefList/CompletedDrefTable/index.tsx
* Fix completed operation column order in expandable
=> Fix expandable column DREF account page

CHANGELOG.md, package.json, src/root/components/DrefPdfDocument/NeedIdentifiedOutput/index.tsx, src/root/components/OperationalUpdatePdfDocument/NeedIdentifiedOutput/index.tsx, src/root/components/OperationalUpdatePdfDocument/index.tsx
* Add identified gap in DREF and operational pdf
=> Add identified gaps in export

CHANGELOG.md, package.json, src/root/components/contact-row.js
Refers to https://github.com/IFRCGo/go-frontend/issues/2814
=> No separate in contact field

src/root/components/DrefApplicationList/ActiveDrefList/ActiveDrefTable/index.tsx, src/root/components/DrefApplicationList/ActiveDrefList/index.tsx, src/root/components/DrefApplicationList/CompletedDrefList/CompletedDrefTable/index.tsx, src/root/components/DrefApplicationList/useDrefApplicationListOptions.ts
* Add date of approval in completed DREF
* Fix status type display
=> Fix DREF Account Page

src/root/components/DrefApplicationList/ActiveDrefList/ActiveDrefTable/index.tsx, src/root/components/DrefApplicationList/ActiveDrefList/styles.module.scss, src/root/components/DrefApplicationList/CompletedDrefList/CompletedDrefTable/index.tsx
* Improve table and dropdown conditions
* Work on feedback (by: anamariaescobar)
=> Improve condition in DREF account page

src/root/components/BasicModal/index.tsx, src/root/components/DrefApplicationList/ActiveDrefList/ActiveDrefTable/index.tsx, src/root/components/DrefApplicationList/ShareUserModal/index.tsx, src/root/components/DrefApplicationList/ShareUserModal/styles.module.scss, src/root/components/DrefApplicationList/styles.module.scss, src/root/components/Header/styles.module.scss, src/root/components/OperationalUpdateExport/index.tsx, src/root/components/TableActions/styles.module.scss
* change user search component in active DREF share modal
=> Fix user search DREF share 

src/root/components/RiskImminentEventMap/GDACSEventMap/PointDetails/index.tsx, src/root/components/RiskImminentEventMap/GDACSEventMap/PointDetails/styles.module.scss, src/root/components/RiskImminentEventMap/MapFooter/index.tsx, src/root/components/RiskImminentEventMap/PDCEventMap/index.tsx, src/root/types/risk.ts
* Add severity data GDACS
* Fix the Map footer tooltip
=> Fix Risk Watch Imminent

src/root/components/DrefApplicationList/ActiveDrefList/ActiveDrefTable/index.tsx, src/root/components/DrefApplicationList/ActiveDrefList/index.tsx, src/root/components/DrefExportButton/index.tsx
* Fix table dropdown when ops and final report
* Fix DREF export button
*  Fix create new stage
=> Fix dropdown table list DREF Account Page

src/root/components/DrefApplicationList/ActiveDrefList/index.tsx, src/root/components/DrefApplicationList/ActiveDrefList/styles.module.scss, src/root/components/DrefApplicationList/CompletedDrefList/CompletedDrefTable/index.tsx
* Fix table status on the DREF account page
=> Add status in DREF

src/root/components/DrefApplicationList/ActiveDrefList/ActiveDrefTable/index.tsx, src/root/components/DrefApplicationList/CompletedDrefList/CompletedDrefTable/index.tsx, src/root/components/DrefApplicationList/index.tsx, src/root/lang.js
* DREF Account Page
*  Change table heading
* Move static strings to the translation file
=> DREF table heading improvements

src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefOperationalUpdateForm/Overview/index.tsx, src/root/views/DrefOperationalUpdateForm/common.tsx, src/root/views/DrefOperationalUpdateForm/index.tsx, src/root/views/DrefOperationalUpdateForm/useDrefOperationalUpdateOptions.ts, src/root/views/FinalReportForm/index.tsx
* Remove validate on loan type DREF
* Fix language mismatch conditions
=> Fix DREF loan type

src/root/components/ThreeWForm/index.tsx, src/root/components/mobile-navbar.js, src/root/components/navbar.js, src/root/utils/common.ts, src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefOperationalUpdateForm/index.tsx, src/root/views/FieldReportForm/index.tsx, src/root/views/FinalReportForm/index.tsx, src/root/views/FlashUpdateApplicationForm/index.tsx
- Addresses
#2821  
- Add utility function to check translation language
- Improve language mismatch in the all form
- Remove covid tracking from create report dropdown
=> Update: language mismatch

package.json, src/index.js, src/root/Multiplexer/index.js, src/root/components/SelectInput/index.tsx, src/root/components/emergencies/overview.js, src/root/components/page-footer.js, src/root/index.js, src/root/lang.js, src/root/sentry.ts, src/root/utils/constants.js, src/root/utils/format.js, src/root/utils/store.js, src/root/views/FieldReportForm/ContextFields/index.tsx, src/root/views/FieldReportForm/index.tsx, src/root/views/field-report.js, src/root/views/home.js, yarn.lock
Addresses: https://github.com/IFRCGo/go-web-app/issues/32, https://github.com/IFRCGo/go-frontend/issues/2582
=> Fix sentry envelop timeout

src/root/sentry.ts
Depends on: https://github.com/IFRCGo/go-api/pull/1842
=> Enable tracing origins for sentry

README.md
dsgocdnapi.azureedge.net -> goadmin-stage.ifrc.org
=> Fix Staging URL in README

README.md
=> Updating README with NodeJS version and dockerized start

CHANGELOG.md, package.json, src/root/components/FinalReportPdfDocument/ContactInformationOutput/index.tsx, src/root/components/FinalReportPdfDocument/FinancialReportFileOutput/index.tsx
-    Fix crop text for the financial report
=> Hotfix: Fix financial preview text crop

src/root/components/RiskImminentEventMap/GDACSEventMap/index.tsx, src/root/components/RiskImminentEventMap/MapFooter/index.tsx, src/root/components/common/tooltip.js, src/root/components/connected/personnel-table.js, src/root/views/Country/RiskWatch/ImminentEventsGDACS/index.tsx, src/root/views/RegionalRiskWatch/ImminentEvents/ImminentEventsGDACS/index.tsx, src/styles/global/_tooltip.scss, src/styles/main.scss
- Fix the GDACS zoom issue
- Fix the emergency surge personnel table tooltip
- Fix the home figures card tooltip
=> Fix risk watch zoom and tooltip issues

src/root/hooks/useBasicLayout/styles.module.scss, src/root/lang.js, src/root/views/DrefApplicationForm/index.tsx, src/root/views/DrefApplicationForm/styles.module.scss
Addresses: https://github.com/IFRCGo/go-frontend/issues/2867
=> Restrict DREF application form to english language

src/root/components/FinalReportPdfDocument/FinancialReportFileOutput/index.tsx, src/root/utils/pdf/pdfStyles.ts
- #2870 
- https://github.com/toggle-corp/ifrc-go-meta/issues/284
- Add link for the final report in pdf export
=> Add financial report link in export

src/root/components/FinalReportPdfDocument/FinancialReportFileOutput/index.tsx
- #2870 
- Change financial report link label in export
=> Change financial report link label in export

CHANGELOG.md, package.json, src/root/components/FinalReportPdfDocument/FinancialReportFileOutput/index.tsx, src/root/utils/pdf/pdfStyles.ts, src/root/views/Country/index.js
The '/admin' was missing in country edit link.
=> Fix country editing link to Admin page

src/root/components/FinalReportPdfDocument/EssentialInformationOutput/index.tsx
Refers to https://github.com/IFRCGo/go-frontend/issues/2887
=> Hide Main Donors title

src/root/components/DrefApplicationList/ActiveDrefList/ActiveDrefTable/index.tsx
fixes issues as mentioned in https://github.com/toggle-corp/ifrc-go-meta/issues/215#issuecomment-1689321755
=> Dref Allocation Form Fixes
