IFRCGo/go-frontend

app/assets/scripts/main.js, package.json, yarn.lock
cc @danielfdsilva this swaps out the es6-promise polyfill for babel-polyfill, which includes support for `object.assign` in old Safari.
=> Polyfill es6, not just promises

app/assets/scripts/utils/utils.js
These are coming in as auto-generated emergencies from the GDACs ingest, which don't automatically set a disaster type property. I'm showing this as `N/A` on the emergencies page.
=> Handle emergencies with no dtype set

app/index.html, gulpfile.js
This is because on pages like `/emergencies/7` the proxy causes the assets route to translate as `/emergencies/assets/...` which is wrong. This should address that.
=> Use leading slash before assets

app/assets/scripts/components/deployments/map.js
These two countries don't have ISO2 codes in our data.
=> Patch France and Norway

app/assets/scripts/views/emergency.js
Appeals docs are public always. Sit reps show login prompt if you're not logged in.
=> Show the login prompt for sit reps

app/assets/scripts/utils/field-report-constants.js
Close #217 
Remove the local storm disaster type.
Fix spelling of "Flood".
=> Fix disaster types to match api

app/assets/scripts/components/connected/featured-emergencies.js
There were two decimal numbers in funded/requested, and the addition made them a strange creature (0398154.91253671.00 and 05425000.00253671.00), which had two+two decimal points, so could not be treated as numbers and can not be divised with each other.
=> Numeric addition of floats to have percentage

app/assets/scripts/utils/utils.js
In the old version (as somehow my local debug environment used) in /api/v2/event/ the dtype was a number. In the new version (due to verbose CSV) the dtype is a structure, like
```
"dtype": {
"name": "Other",
"summary": "",
"id": 13
},
```
=> Using dtype as a structure instead of number

app/assets/scripts/actions/index.js, app/assets/scripts/reducers/districts.js, app/assets/scripts/reducers/index.js, app/assets/scripts/schemas/field-report-form.js, app/assets/scripts/views/field-report-form/data-utils.js, app/assets/scripts/views/field-report-form/index.js
Have made changes to the Field Report form as per https://github.com/IFRCGo/go-frontend/issues/642:
- Allow a user to only select a single Country
- When user selects Country, populate `Areas` dropdown with `Areas` of that country
- Allow user to select multiple `Areas` and save
- Handle loading of `Areas` correctly.
The form seems to work fine to add as well as edit, but it would be nice to test a bit more.
We may want to consider adding some information about the `Areas`  in the Field Report summary. To discuss.
It would probably be good to get this on `stage` soon, though it requires this backend PR to be merged first: https://github.com/IFRCGo/go-api/pull/457
@mankamolnar will be great if you can have a quick look - if it seems okay to you, we can chat on the call tomorrow and figure …
=> Select areas while entering Field Report details

gulpfile.js, package.json, yarn.lock
@szabozoltan69 @mankamolnar this should fix the uglify issues .. but we should also test the site after this builds that everything looks okay, since we will be using an updated javascript minifier (ideally, it should not break anything.)
=> use gulp-uglify-es instead of gulp-uglify to fix uglify issues

app/assets/scripts/components/map/emergency-map.js
Use a 2-step approach - extract image data from GL canvas, write to an <img /> tag, and then use html2canvas to export, so html2canvas does not fail trying to render out the GL map.
Fixes #767
=> Fix Emergency Map export in non-Chrome browsers

app/assets/scripts/views/countries.js
Temporarily hide the map on the country page until we figure out exactly what we want to do with it.
Fixes #775
=> comment out map on country page, fixes #775

app/assets/scripts/views/emergency.js
Fixes regression that broke appeal documents rendering after implementing the new layout for response documents.
=> fix rendering of appeal documents on emergency page

app/assets/styles/home/_global.scss
#803 To prevent a single tile from wrapping on large screens, I added changed the flex to nowrap. The wrap is essential for the medium screens so I added a media-query specifying the nowrap setting. 
This should address the wrapping of the single tile on Safari.
=> adds flex nowrap for large screens

app/assets/scripts/components/map/home-map.js
#765 This updates the text on the home page map to say 'presentation mode' instead of 'expand map'
=> changes map expand btn text

app/assets/scripts/components/per-forms/per-form-component.js
I'm having a bit of a hard time figuring out testing this, see https://github.com/IFRCGo/go-frontend/issues/808#issuecomment-529891501
But, from what I can tell, this *should* work.
@necoline can I ask you to give this a quick look and let me know if this seems sane? We want to (temporarily) hide the language selector on these forms as per #808 .
I will ask the team to test thoroughly once we merge this to develop to check that this does indeed work.
=> hide language selection drop-down on PER forms, fixes #808

app/assets/scripts/utils/get-new-map.js
Quick fix to show labels. Changes maxZoom on the map from 6 to 8.
=> allow maxZoom 8 to get country labels to show properly

app/assets/styles/home/_global.scss
Updates spacing between key figures on region page per request on #852 
Home page design is unaffected:
=> removes space between cards on region

app/assets/scripts/views/field-report-form/data-utils.js
Fixes an over-sight, forgot to remove references to hard-coded actions.
=> remove unneeded reference to hard-coded actions

app/assets/scripts/components/highlighted-operations/index.js, app/assets/scripts/components/highlighted-operations/operation-card.js, app/assets/styles/home/_global.scss
#846 
This adds a bit of css hackery that adds different classes depending on list length. 
Looking forward to rewriting this to be a carousel
3: 
4:
5:
6:
=> updates styles to accomodate 4-6 ops

app/assets/scripts/schemas/field-report-form.js, app/assets/scripts/utils/field-report-constants.js, app/assets/scripts/views/field-report-form/cmp-source-estimation.js, app/assets/scripts/views/field-report-form/data-utils.js, app/assets/scripts/views/field-report-form/index.js, app/assets/styles/field-report/_form.scss
Addresses the following fixes:
- Change `Risk` to `Risk Analysis` in stepper for Early Warning
- Change source label `RCRC` to `Red Cross / Red Crescent` - fix styling for labels to accomodate longer labels.
- Adds to additional fields to the Field Report as per #880 
@necoline these are mostly minor fixes, am going to go ahead and merge so things can be tested, but please let me know if anything seems off to you / can be improved.
=> Field Report Fixes

app/assets/scripts/actions/index.js, app/assets/scripts/components/highlighted-operations/index.js, app/assets/scripts/views/countries.js
This PR implements the filter to show Highlighted Operations on the Region page that are marked as `if_featured_region` on the backend.
@necoline I wasn't sure what the behaviour should be on the Country page. I have commented it out in the code for now, and would ideally just drop it from the country page, but we should discuss this.
I find it a bit awkward that I'm re-using the `GET_FEATURED_EMERGENCIES` action type in the action: https://github.com/IFRCGo/go-frontend/compare/feature/filter-region-ops?expand=1#diff-5c355adac55012fbbb2981b6d27b1742R166 - I think it's probably fine, but @necoline let me know if you think that should be done differently.
This seems to work and I tested locally with the backend. I am a bit confused by the `getFeaturedEmergenciesDeployments` action and the …
=> filter highlighted operations by is_featured_region flag

app/assets/scripts/components/form-elements/input-select.js, app/assets/scripts/views/field-report.js
Various changes to show all the data from the field report submission on the field report frontend:
- Fixes #896 
- Fixes #895 
- Render numeric details conditionally based on EVT or EW
- Add `forecast_based_action` to planned response fields
- Add `other_sources` field to display
=> Fixes for Field Report frontend

app/assets/scripts/utils/field-report-constants.js, app/assets/scripts/utils/format.js, app/assets/scripts/views/field-report.js
Implements:
- Change `Early Warning` to `Early Warning / Early Action` in field report form
- Change `Expats / Delegates` to `Delegates`
- Add `Requests for Assistance` to field report frontend
cc @mmusori
=> minor text changes on field report form

app/assets/scripts/views/field-report-form/index.js, app/assets/scripts/views/field-report.js
- Change `Planned Response` to `Planned Interventions` for EW reports.
- Fix bug of not showing EW specific numeric data on EW field report frontend
- Handle showing `--` if no pop centre exists
cc @mmusori
=> Field Report changes + bugfix

app/assets/scripts/views/emergency.js
Fixes display of Early Warning Field Report data on the Emergency page.
Needs https://github.com/IFRCGo/go-api/pull/564 to be merged first.
Refs #833
=> show EW data conditionally on emergency page

app/assets/scripts/views/preparedness.js
This adds an error message for missing country details on per form
At one point during testing a form was created without a country. I'm not sure how this happen. Possible causes could be:
- A faulty form was creating during development
- #918 mentions the country dropdown list for PER forms includes national societies that don't exist. It might be possible that the page offers the option to create a form with no country code
This solution does not solve for the creation of a form without a country. 
It prevents the rendering of a form that has no country without breaking any other functionality on the page.
This fix was included in #941 but I'm breaking it out to a separate PR so that we can push it through the approval stage quicker
=> adds error handle for perForm

app/assets/scripts/components/map/per-map.js, app/assets/scripts/components/map/per-map/explanation-bubble.js, app/assets/scripts/components/map/per-map/factory/marker-layer-stylesheet-factory.js, app/assets/scripts/views/preparedness.js, app/assets/styles/home/_global.scss
Changes the map layers to show the phases rather than the section of the form completed. I added a 'incomplete' option which represents any form that has not completed any phase. I don't know if this is a realistic scenario. I know that some of our forms created for testing fall in that category but that might be due to the fact that these forms were not completed as intended. 
I think we should definitely have a fallback color in the case that users do not complete a phase, but I'm not sure if it should be included in the legend
#844
> The map on the PER page currently shows information on the PER forms that have been completed by a National Society. The request from the PER team has been to have the map instead display the PER phase that the NS has last completed.
_Please describe in …
=> changes layer to display phase

app/assets/scripts/components/per-forms/per-form-component.js
#946
I left a variable definition outside of the conditional that checked for existence of the `epiComponent`
Switching these lines fixes the bug:
=> moves variable def inside conditional

app/assets/scripts/components/per-forms/form-data/a3-2/english-data.js, app/assets/scripts/components/per-forms/form-data/a3-2/french-data.js, app/assets/scripts/components/per-forms/form-data/a3-2/spanish-data.js, app/assets/scripts/components/per-forms/form-data/a3/english-data.js, app/assets/scripts/components/per-forms/form-data/a3/french-data.js, app/assets/scripts/components/per-forms/form-data/a3/spanish-data.js
- Switches the language of A3 and A3-2 since they were somehow reversed in the course of the refactor
#953
The mismatch of content resulted in a misleading url which is one of the key indicators of the A3 category since the titles are the same.
=> switches language btwn 3 & 3-2

app/assets/scripts/components/map/per-map/explanation-bubble.js
Change legend text on per map to "Current PER phase" as per https://github.com/IFRCGo/go-frontend/issues/844#issuecomment-581823196
@necoline am going ahead and merging this in as it's a minor change.
=> [minor] change PER map legend text

app/assets/scripts/components/country/preparedness-column-graph.js, app/assets/scripts/components/country/preparedness-summary.js, app/assets/scripts/components/preparedness/global-preparedness-highlights.js, app/assets/scripts/utils/get-per-components.js
- updates fallback for `getShortComponent` to apply the `.shift()` to the parent function rather than the children
- applies the fallback to `defaultValue` to all outputs of `getPerComponent` rather than just the output of `getShortComponent`
This should take care of any faulty requests to `PerComponents`
=> adds fallback to all 'getPerComponent' results

app/assets/scripts/components/connected/personnel-table.js, app/assets/scripts/components/highlighted-operations/index.js, app/assets/scripts/views/deployments.js
Issue: #965 
Changes:
- 'RR' to 'Rapid Response' in the Deployments table.
- Adds 'RR' and 'FACT' values together on the Deployments page and in the Highlighted Operations on the homepage.
Before merging:
=> Add FACT and Rapid Response values together

app/assets/scripts/components/map/per-map/factory/marker-layer-stylesheet-factory.js
Fixes bug where countries that had their phase as 0 showed up as black, when they should be incomplete / grey.
=> fixes #844 - black dot for phase 0 instead of grey

app/assets/scripts/components/highlighted-operations/index.js, app/assets/scripts/components/highlighted-operations/operation-card.js
=> Zeros to dashes if no data for Highligted ops.

app/assets/scripts/components/per-forms/per-form-component.js, app/assets/scripts/components/per-forms/per-form.js
Fixes bug where if a form component did not have an `epiComponent` defined and you selected `Yes` for Epidemics on a PER form, the page would crash.
Refs #994
=> allow components to not have epiComponent defined, ref #994

app/assets/scripts/views/field-report.js
Fixes display of Information Bulletin Published on Field Report frontend - #984 - thanks for the catch @teklal 
Also changes the wording for the Potential Date of Impact field to Forecasted Date of Impact.
=> fix information published display on frontend, change wording for for date

app/assets/scripts/views/deployments.js, app/assets/styles/global/_inpages.scss
@batpad There could be a more sophisticated way to do login in `.scss` files for these kind of stuff. I basically just copied the `.stats-list` section as a whole and changed `@include column(4/12);` to have only 3 columns (since `.stats-list` is used by the Emergencies page too).
**Feel free to change/fix or comment your thoughts please before merging this.**
=> Added RDRT into RR for Deployments stats

app/assets/scripts/views/countries.js
Disaster Types were missing from the Operations table on the Country-Edit page.
=> Fix Disaster Type missing for ops. on Country page

app/assets/scripts/actions/index.js, app/assets/scripts/views/emergencies.js
Changed back the values on top of Emergencies page to show the correct values of 'last 30 days' instead of 'last 90 days'.
=> Last 3 months Emer. back to last month Emer.

app/assets/scripts/views/field-report-form/index.js
#1056 
deployed: https://ifrc-go-fix-1056-field-report-continue.surge.sh/
Removes 'Save' from the 'Continue' button at the bottom of the report section
=> removes 'save'

app/assets/scripts/utils/utils.js, app/assets/scripts/views/emergency.js, package.json, yarn.lock
This PR should go along with https://github.com/IFRCGo/go-api/pull/639
cc @batpad
=> Response docs ordering

app/assets/scripts/views/emergency.js
Refs #1081 - should fix showing Alerts table on Emergency page when Emergency pages are navigated to directly.
=> Show Alerts on Emergency page when navigated to directly.

app/assets/scripts/components/emergencies/snippets.js, app/assets/scripts/views/emergency.js
Addresses #1009. Should be merged after https://github.com/IFRCGo/go-api/pull/650
@necoline  - let me know what you think, I think the way I'm managing the tabs in the state could probably be more elegant. 
One thing I'm struggling with which we should absolutely fix is this: https://github.com/IFRCGo/go-frontend/blob/feature/multiple-tabs/app/assets/scripts/views/emergency.js#L116 -- if we do this on componentDidMount, the tabs aren't populated yet so it always resolves to `#details`.
cc @batpad
=> Multiple tabs

app/assets/scripts/components/form-elements/checkbox-group-actions.js, app/assets/scripts/components/form-elements/checkbox-group.js, app/assets/scripts/views/field-report-form/cmp-action-checkboxes.js
@necoline Could you look into this please if there is any other better way to handle this issue? This PR is just the ugly/fast version of fixing the problem by me rolling the changes back of https://github.com/IFRCGo/go-frontend/commit/1ab561ad4de7f5d8200c027f8f911d198b04127c and duplicating the new version of `FormCheckboxGroup` -> `FormCheckboxGroupActions` to use for Field Reports.
Ticket: https://github.com/IFRCGo/go-frontend/issues/1130
cc @batpad Just in case if Neco was not available this week.
=> Duplicated FormCheckboxGroup for Actions

app/assets/scripts/utils/field-report-constants.js, app/assets/scripts/views/field-report-form/index.js
- adds helper text for title and disaster type
#1135 
test url https://ifrc-go-fix-1135-epi-guidance-text.surge.sh/reports/new
=> updates step 1 descriptions for covid

app/assets/scripts/components/global-header-banner.js, app/assets/scripts/views/app.js, app/assets/styles/global/_global-banner.scss, app/assets/styles/main.scss
Addresses #1007 , adding a site-wide banner with, currently, a hard-coded link to the COVID-19 emergency.
Testing URL: https://ifrc-go-feature-1007-covid-banner.surge.sh/
cc @GregoryHorvath @teklal @LukeCaley
=> #1007 - add global header banner with link to covid emergency

app/assets/scripts/views/field-report-form/data-utils.js, app/assets/scripts/views/field-report.js
Fixes issue where if you put in an Actions summary, but did not select any checkboxes (or if there were no checkboxes for that actions section), it would not save the summary.
Now, it still creates a new ActionsTaken entry in the database if there are no actions selected, but only if the summary field is not empty, and this will display on the field report page, appear in the API, etc.
=> allow actions to be saved with summary even no action checkboxes selected

src/root/components/connected/emergencies-table.js
Previous default interval was set to `recentInterval` which is 30 days.
Surge: https://ifrc-go-feature-1132-recent-emergencies.surge.sh
Closes #1132
=> Change interval for country emergencies to a year

src/root/index.js, src/root/views/field-report.js
Closes #1118
- For `/reports/all` it will show all the public FRs when you're not logged in
- For `/reports/:id` it will
- show the report if it's public and you're not logged in
- show an error screen if you don't have the correct permissions
Let me know if the text copy should change. 
Surge: https://ifrc-go-fix-1118-public-private-frs.surge.sh
=> Fix permissions for public FRs

src/root/views/register.js
Changed wording in non-whitelisted domains text box to be clearer and include Red Crescent.
A small quick win for clarifying/improving the registration process #1233
=> Changed wording in non-whitelisted domains note

src/root/utils/utils.js
Previously registering domains like `x@ifrc.orgwwwww` would work, now they wont.
=> Email domain now only valid if it's an exact match

src/root/utils/field-report-constants.js, src/root/views/field-report-form/index.js
Link: #1226 
- Fixes title help text 
- Fixes help text for two activity sections
---
Surge: https://ifrc-go-fix-1226-fix-covid-language.surge.sh
=> Fix language for activities in step 3

src/root/components/emergencies/snippets.js
Link: #1232 
Surge: https://ifrc-go-fix-1232-remove-additional-graphics.surge.sh
=> Remove header from tabs on emergency page

src/root/views/field-report-form/index.js
Missed to handle the 'Disaster type' field with the previous changes to fields being disabled by the start of creating a Field Report.
=> Disable disaster type from the start

src/root/views/emergency.js
To complete #1118 we need to be able to see public FRs on emergency pages in the "Field Reports" tab. I removed the "must login" logic, but I didn't know how to associate two FRs to one emergency to see what happens when there is a private FR as well as a public FR. Could you test @batpad @karitotp ?
https://ifrc-go-fix-1118-emergency-pages.surge.sh/emergencies/3833#details
=> Allow public FRs on emergency pages

src/root/views/emergency.js
This should fix the frontend component to this ticket comment: https://github.com/IFRCGo/go-frontend/issues/1118#issuecomment-635918910
Is dependent on changes to the backend. @GregoryHorvath will be great if you could test this locally with the backend changes, or deploy the backend to staging and we can test this. Thanks!
=> hide field reports on emergency page based on user permissions

src/root/components/header.js
Increased the frequency when Elasticsearch is picking up the input into the searchbox from `150ms` -> `500ms`. It feels like a reasonabe middle ground for both fast- and slow-typers.
Should help a bit with: https://github.com/IFRCGo/go-frontend/issues/989
=> Increase Elasticsearch setTimeout

src/root/components/per-forms/form-data/README.md, src/root/components/per-forms/form-data/form_data_to_json.js
Adds a helper `node` script to re-generate a JSON for the PER questions, that can be plugged into the backend.
Refs #1137
=> add script to regenerate json of questions to use in backend, refs #1137

src/root/views/field-report-form/index.js
Added a timeout (`350ms`) for the 'Create Field Report' page's Emergency dropdown too.
Ref.: https://github.com/IFRCGo/go-frontend/issues/989
=> Added timout to ElasticS. on Create FR too

src/root/views/field-report-form/index.js
`nextProps.fieldReportForm.error` object could have a key like `start_date` if that field has an error, so it wouldn't be good to list all fields here. With this basically it doesn't matter how many fields may have errors it will only display the first and if that's fixed it will show the second (if there is), etc.
This only affects the submission errors, the errors happening at record creation should already say the error was.
cc @teklal
=> Error message fix for Create Field Report form

src/root/views/table.js
Fixes a silly error causing the breadcrumbs to be broken on the `All emergencies` and `All operations` pages.
=> fix breadcrumbs on table views without filters

CHANGELOG.md, package.json
Just added a quick release note for the backend release -- it's a bit awkward since we are not doing a corresponding frontend release for this hotfix, but is likely useful to have this release note.
=> add release note for backend hotfix

src/root/views/register.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1233#issuecomment-658237127
`a.value - b.value` wasn't working
=> Fix for registration dropdown

src/root/components/common/key-figures-header.js, src/root/components/connected/presentation-dash.js, src/root/views/home.js, src/styles/home/_global.scss
Addresses #1376 
@imohkay moved highlighted ops below key figures and also handles hiding Highlighted Ops on full-screen so it doesn't interfere with Presentation mode.
If this looks okay to you, let's merge to develop.
=> Move highlighted ops below Key Figures on home-page

src/root/components/display-table.js
As per #1418, hide pagination if there is only 1 page.
@imohkay could you check this and merge?
=> hide pagination if there is only 1 page of results, across all tables #1418

src/root/views/emergency.js
Addresses #1451 - I did not realize there are some cases where the `region` for the country is `null`. Ideally this will be fixed in the data with the new geospatial fixes, for now, working around in code and not displaying the "Region" identifier below the title when region is null.
=> dont crash emergency page if region for country is null

src/root/views/countries.js
Fixes crash on country page if region for country is null.
=> hide link to region below country title on country page if region is null

src/styles/global/_folds.scss
ensure highlighted ops title size matches the other folds' titles
=> #1448: fix highlighted operations title

src/styles/emergency/_global.scss
=> #1469: fix for action button height on specific emergency page

src/root/components/connected/presentation-dash.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1443
The home page fired some duplicate requests. The `AppealsTable` component already has the necessary action:
https://github.com/IFRCGo/go-frontend/blob/22407768ad312dfbc51546ecc978ce7ba87f276e/src/root/components/connected/appeals-table.js#L54
=> Removed duplicate getAppealsList call

src/styles/home/_highlighted-emergencies.scss
Relates to #1478 issue on mid-sized desktops, when the number overflows the column.
=> #1478: update high ops number value to be smaller on medium breakpoint

CHANGELOG.md, package.json, src/root/views/field-report.js
Fixes a copy-paste error in the field report frontend, should solve #1508 . 
cc @nanometrenat
=> fix incorrect string mapping in field report frontend, refs #1508

src/root/Multiplexer/index.js, src/root/actions/index.js, src/root/lang.js, src/root/reducers/index.js, src/root/reducers/resend-validation.js, src/root/views/login.js, src/root/views/resend-validation.js
Ref.: https://github.com/IFRCGo/go-api/issues/737
- Added action, reducer, route and view for being able to re-send the validation email if the user didn't get it
- Added this to the login page's "Forgot password" section
- Added the required translation strings
Backend PR: https://github.com/IFRCGo/go-api/pull/840
=> Re-send validation email

src/root/views/Covid19ThreeWSankey/Filters.js, src/root/views/RegionalThreeW/map.js, src/root/views/RegionalThreeW/ns-activities-filters.js
Fixes an issue where we needed to add all variables used in the function as dependency to the `useEffect` and `useMemo` methods, to get lint / build to pass.
@frozenhelium I'm going to go ahead and merge, but please could you take a look and let me know if this seems correct?
cc @geohacker
=> fix useEffect dependency issues, fix lint

src/root/views/field-report.js
Fixes the case of global loading not disappearing on https://dsgoproxyapp.azurewebsites.net/reports/9637 when logged in.
=> fix stuck loading state on view field report page

src/root/components/header-region-button.js, src/root/components/per-forms/per-documents.js, src/root/components/preparedness/factory/national-societies-engaged-per-graph-data-factory.js, src/root/selectors/index.js, src/root/views/countries.js, src/root/views/emergency.js, src/root/views/region.js, src/root/views/table.js
Part of https://github.com/IFRCGo/go-frontend/issues/1534. Uses a label for each region from the API instead of the enum name.
cc @batpad
=> use region label instead of enum name

src/root/utils/field-report-constants.js, src/root/views/account.js, src/root/views/register.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1541
- Removed duplicate `getCountries()` call since the init has it now
- Refactored `countries` callback so it handles both a normal `countries` paramter or one changed with `countriesSelector`
=> Fix Countries dropdownlists (account, register pages)

src/root/views/account.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1491#issuecomment-684764151
This should fix the loading issue, at least I couldn't reproduce the bug after this change. Needs testing on staging as well for sure.
=> Fix of hiding the global loading for Account page

src/root/utils/utils.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1550
- `console.log()`-ed error: `TypeError: Cannot read property 'coordinates' of null (key-figures-header.js:74)`
Also keep in mind https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Browser_compatibility
I've ran into issues with this with the Tableau Web Data Connector, because the application uses some older version of the Chromium engine.
@geohacker Feel free to take over if you think this wouldn't fix the whole issue.
=> Fix homepage key-figures (null error for centroid)

src/root/reducers/eru-owners.js, src/root/views/RegionalThreeW/map.js, src/root/views/preparedness.js
Followup of: https://github.com/IFRCGo/go-frontend/pull/1551
Fixes the remaning possible null errors of the `centroid` object.
=> Fix centroid nullchecks

src/root/lang.js
Refs #1395 - removes extra 'the' in map export disclaimer text.
@frozenhelium sorry, this means a minor change to the english strings - but it's just removing a "the", hopefully it doesn't cause any confusion with translation workflows.
=> update disclaimer text on maps, refs #1395

src/root/config.js, src/root/utils/field-report-constants.js, src/root/views/field-report-form/index.js
related to https://github.com/IFRCGo/go-api/pull/883
This PR ensures that the country dropdowns now only show countries that are independent.
=> show only independent countries in the country dropdown

src/root/utils/field-report-constants.js
Refs #1499 - remove empty country at the top of the country dropdown list on the field report form
cc @geohacker
=> refs #1499, remove extraneous empty country at top of select

src/root/components/LanguageSelect/styles.module.scss
Aligns the Language dropdown with the other elements of that line.
=> Remove border-bottom from Lang. Select style

src/root/views/account.js
Refs #1577 
This was a silly bug, surfaced when a user had a country element in the notifications array.
=> fix parameter order on account page, refs #1577

src/root/components/header-region-button.js, src/root/lang.js
@frozenhelium let me know if you'd rather I create a new variable in lang.js instead of re-using the regionsOverview string.
=> fix for translating Regions string in nav header

src/root/components/connected/emergencies-dash.js, src/root/components/connected/presentation-dash.js, src/root/components/map/common/map-component.js, src/root/components/map/deployments-map.js, src/root/components/map/emergencies-map.js, src/root/components/map/main-map.js, src/root/selectors/index.js, src/root/utils/country-labels.js, src/root/utils/special-map-labels.js, src/root/views/CountryProfile/Map.js, src/root/views/CountryProfile/PopulationMap.js, src/root/views/CountryProfile/index.js, src/root/views/RegionalThreeW/index.js, src/root/views/RegionalThreeW/map.js, src/root/views/ThreeW/map.js, src/root/views/deployments.js, src/root/views/region.js
This PR hides the default text layer on Mapbox maps and introduces a custom layer to show country labels based on the users current language selection.
=> Multilingual map labels

src/root/components/connected/alerts-table.js
Fixes display of the Emergency names in the Alerts table for Alerts imported from Molnix (uses the name of the emergency if operation string is empty).
=> fix display of emergency name in alerts table emergency link

src/root/views/countries.js
Refs #1621 - allows Additional Info tab name on country page to be customized in the backend.
=> add custom additional tab label for country page

src/root/components/connected/alerts-table.js
Corrects the shape of the array sent to filter headers to display filters on the surge alerts table correctly.
=> fix alerts table filter texts

src/root/components/admin-area-elements.js, src/root/lang.js, src/root/views/region.js
Fixes a few small things as per #1621 -
- Fix region name in label for national societies count
- Change Additional Graphics to Regional Content in Additional Data tab
- Hide Key figures
- Hides the Additional Info tab if it contains no data
=> Region additional tab fixes

src/root/views/region.js
Add back Key Figures to Additional Info tab, keep logic to not display tab if there are no key figures or region snippets.
=> add back key figures to region pages

src/root/components/country/preparedness-overview.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1667
- Fix issue if there are no PER Assessments for a Country it would crash on the Country-Preparedness tab
=> Fix null Overview for Country Preparedness

package.json, src/root/components/map/main-map.js
Should fix the jankiness when mousing over the map and highlighting countries.
@geohacker -
I commented out a mousemove on the districts layer, which was trying to change the mouse pointer, I think we should avoid that, and I don't think we are really using that, could you check if that looks okay?
I tried playing around with the debounce time a bit - 80ms seemed a good balance point on my machine where it didn't take too long to highlight a country, and there is little or no "jankiness" that existed without the debounce (or seems to exist a bit if I go to say 40ms).
I also added the current highlighted feature to the state and then doing a check, if it's the same feature being moused over, don't call the setFilter etc.. @geohacker can you look if that makes sense?
This definitely feels …
=> debounce map mousemove, also comment out old districts mousemove fn

src/root/components/timeline-charts.js
Fix for:
```
IFRCGo/go-frontend/src/root/components/timeline-charts.js
132:24  warning  Function declared in a loop contains unsafe references to variable(s) 'curDate'  no-loop-func
```
by creating a new scoped variable for the internal for loop
=> Fix loop var declaration in timeline charts and add docs

src/root/components/display-table.js
Ref.: https://github.com/IFRCGo/go-frontend/issues/1749
- Fix nullchecking `showHeader` prop for `DisplayTable`, now defaults to `true`
=> Fix nullchecking showHeader prop for DisplayTable

src/root/views/emergency.js
Given API response that contains the boolean field hide_field_report_map hide the Map component from the page.
Depends on https://github.com/IFRCGo/go-api/pull/962
=> Hides field report map

src/root/components/map/main-map.js
This is because with https://github.com/IFRCGo/go-api/pull/964 we will import a bunch of countries without iso.
cc @batpad
=> check if iso exists before checking equality

src/root/selectors/index.js
This is to ensure that only countries are on the map and in the selector. Fix for why china was in 0,0 on the map.
=> filter for record_type=1 in the countryByIso selector

src/root/views/preparedness.js
Fix issue of translation strings not always showing on PER tabs.
=> get tab strings in function, not in constructor

src/root/views/preparedness.js, src/root/views/region.js
Fixes the first 3 tabs' translations of the Region pages.
cc @batpad
=> Fix tab translations for Region pages

src/root/views/emergency.js, src/styles/emergency/_global.scss
This PR moves the value for the Key Figures in an emergency to the next line, since that content can sometimes get quite lengthy.
=> #1775: Add styling for Affected Population Centres

src/root/views/countries.js
No clue why this works since it's the same here: https://github.com/IFRCGo/go-frontend/blob/82fa1b547846fb59e57cf9b7539b7e63cccf35d4/src/root/views/countries.js#L147
...but it does somehow...
cc @batpad
=> Fix inconsistency between countryIds

src/root/lang.js, src/root/views/countries.js
- Change label 'Open Surge Positions' to 'Open Surge Alerts' - https://github.com/IFRCGo/go-frontend/issues/1638#issuecomment-745151831
- Fix a bug where navigating from one Country page to another using Elasticsearch would retain some data from the previously visited Country - https://github.com/IFRCGo/go-frontend/issues/1788
- Elasticsearch now will also pick up automatically generated (from Field Reports) Emergencies - https://github.com/IFRCGo/go-frontend/issues/989
- Lowered Elasticsearch timeout value from `5` -> `2`, which makes it faster to retry in the case the first search request fails - https://github.com/IFRCGo/go-frontend/issues/989
=> Release v4.5.1

src/root/lang.js, src/root/schemas/register.js, src/root/views/account.js, src/root/views/login.js, src/root/views/recover-account.js, src/root/views/register.js, src/root/views/resend-validation.js, src/styles/components/_common.scss, src/styles/global/_forms.scss, src/styles/global/_inpages.scss, src/styles/home/_global.scss
Ref.: https://github.com/IFRCGo/go-frontend/issues/1663
Backend PR needed: https://github.com/IFRCGo/go-api/pull/994
- Added `email` besides `username` for logins
- Added email to be editable through the user's account page
- Removed `username` from new registrations
- Removed unnecessary functions from the login screen
- Tried to follow the design changes on Login and Registration pages
- "Keep me logged in" functionality is missing
=> Allow login with email besides username

src/root/components/map/home-map/filtering/filtering-processor.js
Fixes bug when filtering on home-page by Emergency Type would filter the appeal amounts, but not hide points on the map that did not have any appeals / emergencies with the filter applied.
This fixes it to hide points on the map if there are no appeals associated with the point after filtering.
cc @geohacker
=> ensure filtering points on home-page removes points from the map

src/root/components/connected/personnel-table.js, src/styles/components/_common.scss
Fixes the positioning of the line representing "today" on the Personnel Deployments table / chart, refs #1837. This is a visual / CSS fix and should be safe to merge in.
@frozenhelium - could you give a review? Knowing that the overall code for this complex chart squeezed into the existing table structure is all a bit terrible - would be nice to have your eyes on it for a future refactor / to keep in mind whenever we are refactoring the tables and filters - for now, this just fixes the bug of the line appearing in the wrong place, so hopefully is fine to merge. Thanks!
=> fix positioning of today line on surge table, refs #1837

CHANGELOG.md, package.json, src/root/views/about.js
Hotfix for #1980 - adds actual email addresses to the mailto field for emails on the About page.
=> fix mailto in emails on about page, refs #1980

src/root/components/connected/alerts-table.js, src/root/components/connected/personnel-table.js, src/root/utils/utils.js
- Fix bugs with display of duration:
- Remove decimals
- Round off to nearest month if days > 25 or < 5
- If start date or end date do not exists, don't show NaN
- Only truncate Position field for Surge Alerts if coming from Molnix
- Add truncation for Position field for Deployments.
=> Miscellaneous fixes for surge alerts table

src/root/utils/utils.js
diff.months was undefined instead of 0 when months are 0, handle.
Fixes duration showing 0 months when duration is 25-30 days.
=> handle when diff.months is undefined

src/root/components/map/deployments-map.js, src/root/lang.js, src/root/reducers/deployments.js, src/root/utils/mergeDeployData.js, src/root/views/deployments.js
=> Update Surge page map with ERUs and Personnel data

src/root/components/connected/alerts-table.js, src/root/views/deployments.js, src/root/views/emergency.js, src/root/views/table.js
Depends on https://github.com/IFRCGo/go-api/pull/1170
Refs #1965 
Add is_active filter for the Surge Alerts table on the Deployments and Emergency pages - show all surge alerts on All Alerts page - depends on https://github.com/IFRCGo/go-api/pull/1170
=> Do not filter out inactive alerts on All Alerts table

src/root/components/Charts/index.js, src/root/components/connected/emergencies-dash.js, src/root/lang.js, src/root/views/deployments.js
- Create separate component TimeLineChart and use it both on deployments and in emergencies page
PR deployed at https://ifrc-go-new-deploy-chart.surge.sh
=> Add "Deployments over the last year" chart to the Surge page

CHANGELOG.md, package.json, src/root/views/deployments.js
Hotfix for ERUs not displaying on the map.
The logic for fetching the different ERU information does seem a bit convoluted and we should inspect it better.
This fixes the display on the map though.
cc @szabozoltan69
=> Hotfix for ERUs not showing on the map

src/root/components/connected/personnel-table.js
Shows the Country Deployed to from the Personnel table, that comes from Molnix.
If that data does not exist, it falls back to showing the country of the emergency the deployment is associated with, so should continue working for old data.
cc @szabozoltan69 there do not seem to be any deployments in staging so was having a hard time testing this exactly. We may need to create some deployments in Molnix and simulate on staging to test that this works as intended - cc @anamariaescobar .
=> show country_to from individual personnel table, refs #2179

src/styles/components/_common.scss
There's probably a better way to do this than using `!important` . This does seem to definitively fix the issue though.
I'm going to go ahead and merge and hot fix this. But would be good to look and see how to perhaps do this cleaner.
cc @imohkay @szabozoltan69
=> force padding-left and right to 0 for personnel table cell, refs #2262

package.json, yarn.lock
There was a dependabot commit that upgraded the version of `ajv` from 5.5.2 to 6.12.3: https://github.com/IFRCGo/go-frontend/commit/01151a7731532d7602b61c5752aa6361f1c7b172
This caused us to bump into this issue: https://github.com/ajv-validator/ajv/issues/941
This caused the error mentioned in #2270 - currently unclear if it might also affect other parts of the site.
For now, this commit just reverts back to the version we were at - i.e. 5.5.2 . In the linked ticket, it seems this problem was introduced in `ajv` in 6.9.0, so we can probably go to something like 6.8.0 .
For now as a hotfix, I'd rather just roll-back to where we were, and we can upgrade to 6.8.0 in the normal release cycle accounting for testing, etc.
cc @szabozoltan69 @tovari @frozenhelium
=> downgrade ajv back to 5.5.2, refs #2270

src/root/views/resend-validation.js
@szabozoltan69 would you be able to test if this seems to fix the issue?
The problem is that `showAlert` also modified the props, causing the `componentWillReceiveProps` to be called in an infinite loop. We should only do that the "first" time the validation data is fetched and not every time. This should handle that.
In general, this `componentWillReceiveProps` stuff is not very good - hopefully we will be able to migrate to the new React Hooks stuff soon.
=> dont go into infinite loop in componentWillReceiveProps

src/root/views/Emergency/index.js
Solves GSS:
Tab should not be visible to those users whose permissions do not match the 3w activities visibility status. For example, if the GO 3w is set to RCRC membership then non-logged in users should not be able to see the empty data
=> Visibility of Activities

src/root/components/EmergencyThreeWForm/index.tsx
Refers to https://github.com/IFRCGo/go-frontend/issues/2467
=> Using districts_details (instead districts) on EmergencyThreeWForm
